Implemented ComboBox
AvaloniaUI/Avalonia pull request #1070
Opened 2017-07-15 01:52 UTC by jp2masa

Closes #205

2017-07-31 21:57 UTC, grokys commented
Thanks @jp2masa! I've been on vacation and just catching up now. I will review this asap!

2017-08-01 23:11 UTC, grokys requested changes
I added a `ComboBoxPage` to the ControlCatalog with a simple ComboBox:

```
<UserControl xmlns="https://github.com/avaloniaui">
  <StackPanel Orientation="Vertical" Gap="4">
    <TextBlock Classes="h1">ComboBox</TextBlock>
    <TextBlock Classes="h2">A combination of a drop down list and a text box control</TextBlock>

    <StackPanel Orientation="Vertical"
                Margin="0,16,0,0"
                HorizontalAlignment="Center"
                Gap="16">
      <ComboBox>
        <ComboBoxItem>Item 1</ComboBoxItem>
        <ComboBoxItem>Item 2</ComboBoxItem>
        <ComboBoxItem>Item 3</ComboBoxItem>
      </ComboBox>
    </StackPanel>    
  </StackPanel>
</UserControl>
```

And when I run I get the following exception:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=Avalonia.Base
  StackTrace:
   at Avalonia.Contract.Requires[TException](Boolean condition) in D:\projects\Avalonia\src\Avalonia.Base\Contract.cs:line 33

```

Could you add a page for the control to the ControlCatalog (or I can push the page I added to your branch if you like) and fix the exception?

2017-08-03 22:09 UTC, grokys requested changes
Thanks for fixing that!

Found another problem - this test fails:

```
        [Fact]
        public void Text_Is_Selected_String_Item()
        {
            var items = new[] { "A", "B", "C", "D" };
            var target = new ComboBox
            {
                Items = items,
                SelectedIndex = 2
            };

            var text = target.GetValue(ComboBox.TextProperty);
            Assert.True(text == "C");
        }
```
You'll see that items can be of any type, they don't have to be `ComboBoxItem`s.

Secondly, could you merge the latest master into your branch? I would do it myself but you don't seem to have granted me write access to your fork branch.

2017-08-03 22:53 UTC, jp2masa commented
I think that ComboBox is only supposed to deal with text, specified in `ComboBoxItem`s. Also, how would `var items = new[] { "A", "B", "C", "D" };` be declared in xaml?

2017-08-04 09:26 UTC, grokys commented
No, that's not quite how it works :) For example you can bind the `ComboBox.Items`. Here's an example:

```
class ViewModel
{
   public string[] Items { get; } = new[] { "A", "B", "C", "D" }
}
```

```
    <ComboBox Items="{Binding Items}"/>
```

This is a very common scenario (more common than using `ComboBoxItem` itself in my experience).

2017-08-07 20:35 UTC, grokys requested changes
A few more things, sorry :(

If I create a ComboBox like this:

```
      <ComboBox MinWidth="128" Text="Custom Text">
        <ComboBoxItem>
          <Panel>
            <Rectangle Fill="{StyleResource ThemeAccentBrush}"/>
            <TextBlock Margin="8">Control Items</TextBlock>
          </Panel>
        </ComboBoxItem>
        <ComboBoxItem>Item 2</ComboBoxItem>
        <ComboBoxItem>Item 3</ComboBoxItem>
      </ComboBox>
```

And select the first item, I get a `System.NotSupportedException` exception thrown, however this works in WPF - the combo box text is set to `System.Windows.Controls.ComboBoxItem`.

Also in WPF if I type the text of an item into the ComboBox, that item becomes selected, which doesn't happen here.

2017-08-07 20:35 UTC, grokys commented on src/Avalonia.Controls/ComboBox.cs
> +                Text = Convert.ToString(item);
I think you can just use `item?.ToString()` here.

2017-08-24 15:51 UTC, aelij requested changes

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Controls/ComboBox.cs
> +                if (item.ToString() == _textBox.Text)
`ToString()` may not represent the item correctly. You need to check `MemberSelector`. Also, `item` may be null.

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Controls/ComboBox.cs
> +                if (item.ToString() == _textBox.Text)
String comparison should be case insensitive

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Controls/ComboBox.cs
> +                if (item.ToString() == _textBox.Text)
If there's no exact match, the first item that starts with the text should be selected. For example, if the list contains "Item1", "Item2", "Item33", , "Item34", when typing "I", "Item1" would be selected, and when typing "Item3", "Item 33" would be selected. If possible, please unit test those.

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Controls/ComboBox.cs
> +            if (!IsDropDownOpen && ((IVisual)e.Source).GetVisualRoot() != typeof(PopupRoot))
The drop down should be opened by the toggle button, not when clicking anywhere else, so I think this check is redundant.

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Controls/ComboBox.cs
> +            Text = item?.ToString();
Again, use `MemberSelector` instead of `ToString()`

2017-08-24 15:51 UTC, aelij commented on src/Avalonia.Themes.Default/ComboBoxItem.xaml
> +    <Setter Property="Padding" Value="2"/>
Add `<Setter Property="Background" Value="Transparent"/>`

2017-08-26 14:45 UTC, grokys commented
@jp2masa thanks for this PR, but judging from the fact that there have been multiple problems, I'm going to make a guess and say that you didn't implement it because you needed the functionality? It's just I'm wondering if an old-style `ComboBox` such as this is even _needed_ in a modern day application?

2017-08-26 15:12 UTC, jp2masa commented
I don't need the functionality. I was just trying to help, so I was looking for up for grabs issues and I decided to try this one.

2017-08-27 13:22 UTC, grokys commented
Hmm yeah, we probably shouldn't have marked that issue as `up-for-grabs` - it's not a simple thing to implement and tbh we probably should have had a conversation about whether it's actually needed. To be fair we do say in our [`contributing.md`](https://github.com/AvaloniaUI/Avalonia/blob/master/docs/guidelines/contributing.md):

> Before You Start

> Drop into our gitter chat room and let us know what you're thinking of doing. We might be able to give you guidance or let you know if someone else is already working on the feature.

Do you want to keep going ahead with this PR? It's probably going to be a long slog unless you have an application that actually _needs_ the functionality as the back-and-forth here has shown.

2017-10-21 18:11 UTC, grokys commented
Ok, I'm going to close this, thanks for your work on it!

2017-10-21 18:11 UTC, closed without merging