Add a IsPressed property to Button
AvaloniaUI/Avalonia pull request #1128
Opened 2017-08-22 16:41 UTC by mterwoord

Right now, it's not possible use the :pressed state for something else, like turning on a light-bulb (iot) for as long as the button is pressed. With this property, this is possible.

2017-08-26 14:50 UTC, grokys requested changes
Looks good! I know I questioned whether we should have an `IsPressed` property in gitter but I see that it exists in WPF so we should add it. Just one small change requested.

2017-08-26 14:50 UTC, grokys commented on src/Avalonia.Controls/Button.cs
>                  PseudoClasses.Add(":pressed");
Now we have this property, we probably shouldn't be adding the `:pressed` pseudoclass ourselves. There's a `PseudoClass` method that can be used to make a pseudoclass shadow a property: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Control.cs#L111

2017-09-09 17:06 UTC, mterwoord commented
@grokys you had a chance to look at this again?

2017-09-12 19:27 UTC, grokys approved these changes

2017-09-12 19:27 UTC, grokys requested changes
Changes look good except CI is failing, possibly because of the change to the Portable.Xaml submodule? Did you intend to commit that change?

2017-09-12 22:38 UTC, grokys approved these changes
Hope you don't mind @mterwoord but I sorted out the submodule problems myself and updated from master, All looking good to merge now!

2017-09-13 06:59 UTC, mterwoord commented
Sorry, didn't intend to change anything there..


2017-09-13 0:38 GMT+02:00 Steven Kirk <notifications@github.com>:

> *@grokys* approved this pull request.
>
> Hope you don't mind @mterwoord <https://github.com/mterwoord> but I
> sorted out the submodule problems myself and updated from master, All
> looking good to merge now!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AvaloniaUI/Avalonia/pull/1128#pullrequestreview-62286729>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAG931epgOD4LrsjZ_NFyM8IcVrORUGuks5shwfUgaJpZM4O-46A>
> .
>

2017-09-13 08:55 UTC, merged