Scrolling improvements
AvaloniaUI/Avalonia pull request #1132
Opened 2017-08-24 20:09 UTC by aelij

* Button ClickMode.Repeat (instead of RepeatButton)
* ScrollBar has {line,page}/{up/down} buttons
* Fixed a bug with mouse wheel coordinates

2017-08-26 14:28 UTC, grokys requested changes
Looks great in general; a few small things could be tidied up, but also I've noticed something that doesn't work quite right: the large change on the scrollbar should be set to the scrollbar viewport size such that clicking the track outside the thumb should scroll by a page. At the moment it scrolls by a fixed amount.

2017-08-26 14:28 UTC, grokys commented on src/Avalonia.Controls/Button.cs
> +        Press
Nit: unneeded change. These things aren't super-important but they do mess with `git blame`. If you can be bothered you can go back and undo changes like this [using git rebase](https://stackoverflow.com/a/1186549/6448).

2017-08-26 14:28 UTC, grokys commented on src/Avalonia.Controls/Button.cs
> +
Nit: added spurious whitespace.

2017-08-26 14:28 UTC, grokys commented on src/Avalonia.Controls/Button.cs
> +                    new Rect(Bounds.Size).Contains(e.GetPosition(this)))
Nit: unneeded change

2017-08-26 14:28 UTC, grokys commented on src/Avalonia.Controls/Button.cs
> +        protected void RaiseClickEvent()
We already have an `OnClick` method which the comments say "Raises the Click event` except it doesn't. We should probably fix that and merge this method into that method instead.

2017-08-26 15:29 UTC, aelij commented
> At the moment it scrolls by a fixed amount.

Actually, it already scrolls by percentage to the viewport size (see [here](https://github.com/AvaloniaUI/Avalonia/pull/1132/files#diff-7a282687ba30b84d4266419956311a8bR196). I just made the default small change 5% and the large 20% :) You're right it should be a whole page.

2017-08-27 14:09 UTC, grokys commented
Also: there are some failing tests.

2017-08-28 18:07 UTC, aelij commented
@grokys I force pushed an update to my branch to clean up unnecessary changes (and rebased onto master).

2017-09-08 10:03 UTC, grokys requested changes
Changes look good, but `Slider` seems to be broken now, at least in ControlCatalog it is for me...

2017-09-12 19:09 UTC, grokys approved these changes

2017-09-12 19:32 UTC, merged

2017-09-14 11:11 UTC, Sorien commented
btw it's intended that scrollbar keys are focusable?

2017-09-14 16:47 UTC, aelij commented
@Sorien no, we should fix that

2017-10-12 23:50 UTC, kekekeks commented
Was #822 fixed by this?

2017-10-13 04:09 UTC, aelij commented
Yep. Closed