[WIP] Init work with Toggle and RadioMenuItem
AvaloniaUI/Avalonia pull request #11441
Opened 2023-05-19 03:45 UTC by maxkatz6

## What does the pull request do?

- [x] Add RadioMenuItem/ToggleMenuItem APIs
- [ ] Polish radio button functionality (i.e. it should work with hierarchy property).
- [x] Add fluent styles for radio/simple menu items
- [ ] Add simple styles for radio/simple menu items
- [ ] Integrate into NativeMenuItem
- [ ] Ensure that it's usable with binding menus
- [ ] Add tests
- [ ] (bonus) Add icon and separator support for the top-level Menu
- [ ] (optional) Remove support for Header="-", but instead generate Separator container depending on the data context

https://github.com/AvaloniaUI/Avalonia/assets/3163374/3512b24a-ed26-4d7b-be39-af3db262d167

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

tbd

2023-05-19 04:19 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0035049-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

2023-05-19 07:49 UTC, grokys commented
> Remove support for Header="-", but instead generate Separator container depending on the data context

Yep, this should now be possible with the recent changes to how container generation works.

2023-05-21 02:06 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0035163-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

2023-07-14 18:55 UTC, IsaacMarovitz commented
Any update on this? Since the release of Avalonia 11, the old workaround of adding a checkbox as a MenuItem Icon doesn't work properly https://github.com/amwx/FluentAvalonia/issues/367

2023-08-09 14:24 UTC, jgcodes2020 commented
Is this PR still being worked on?

2023-11-17 07:25 UTC, jmacato commented
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

2023-11-23 14:53 UTC, toomasz commented
@jmacato Why wasn't it merged? Would be nice to have this feature

2024-01-29 15:20 UTC, grokys requested changes
A few questions inline, and what might be a bug: the native menu in ControlCatalog doesn't seem to display any check icons on win32:

<img width="271" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/1775141/6e513d14-7fa2-4b16-addb-6f47cbd045ed">

2024-02-03 03:33 UTC, maxkatz6 commented on samples/ControlCatalog/ViewModels/MainWindowViewModel.cs
> +                // handle
It's unused now, removed

2024-02-03 03:36 UTC, maxkatz6 commented on src/Avalonia.Controls/MenuItem.cs
> +        protected virtual void OnClick()
Seem to be a leftover from previous changes. Removed this method.

2024-02-03 03:37 UTC, maxkatz6 commented on src/Avalonia.Controls/RadioButtonGroupManager.cs
> +internal interface IGroupRadioButton : ILogical
IRadioButton makes sense.

2024-02-03 03:40 UTC, maxkatz6 commented on src/Avalonia.Controls/MenuBase.cs
> +        protected internal IMenuInteractionHandler InteractionHandler { get; }
No, it's still visible outside of the assembly. I.e. it's not a "private protected".
I need "protected internal" here, so this property could be used in MenuItem class, which doesn't inherit MenuBase.

2024-02-03 03:54 UTC, maxkatz6 commented on src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
> +        private readonly HashSet<Popup> _frozenPopupStates;
Right, accidentally pushed these changes with the rest. 
Extracted these changes in the separated bacportable PR #14462.

2024-02-03 06:07 UTC, maxkatz6 commented on src/Avalonia.Controls/MenuItem.cs
> +        bool IGroupRadioButton.IsChecked
Because of SetCurrentValue call

2024-02-06 08:27 UTC, grokys commented on src/Avalonia.Controls/MenuBase.cs
> +        protected internal IMenuInteractionHandler InteractionHandler { get; }
D'oh. Yeah I read it as `private protected`.

2024-02-06 08:51 UTC, grokys requested changes
Mostly looking good, but I'm still seeing `NativeMenuBar` isn't displaying toggles as in the last review. It should be, right?

<img width="271" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/1775141/6e513d14-7fa2-4b16-addb-6f47cbd045ed">

2024-02-07 08:27 UTC, maxkatz6 commented on samples/ControlCatalog/ViewModels/MainWindowViewModel.cs
> +                // handle
It's an outdated file, I don't see this command in the code

2024-02-14 10:56 UTC, grokys approved these changes

2024-02-14 14:39 UTC, merged

2025-03-02 08:05 UTC, nesteruk commented
Until you bind Radio toggle types to something, the default behavior is absolutely bizarre. It sets the radio button even when there is no code in the application to do so!