Clear mouse capture when control removed.
AvaloniaUI/Avalonia pull request #1210
Opened 2017-10-12 21:26 UTC by grokys

When a captured control is removed from the visual tree, clear the mouse capture.

Note that our capture logic needs to be improved - it shouldn't be possible to capture a non-visible or non-enabled control. This doesn't address that but it does fix the crash in #1203.

Fixes #1203

2017-10-12 22:08 UTC, kekekeks approved these changes
LGTM

2017-10-13 09:06 UTC, danwalmsley commented
Doesn't fix #1203  but still a required fix, LGTM.

2017-10-13 09:06 UTC, danwalmsley approved these changes
LGTM

2017-10-13 09:18 UTC, kekekeks requested changes
It seems that DetachedFromVisualTree is not being called in time or not being called at all.

2017-10-13 09:22 UTC, danwalmsley requested changes
I added some debugging code to see if Capture = null happens, as @kekekeks says, its not getting called.

2017-10-13 10:28 UTC, kekekeks commented
I see several places in AvalonStudio where `OnDetachedFromVisualTree` is overridden without calling the base class. I think we need to fire `DetachedFromVisualTree` event outside of `OnDetachedFromVisualTree`

2017-10-13 12:39 UTC, grokys commented
I've moved raising the events to `OnAttachedToLogicalTreeCore`/`OnDetachedFromLogicalTreeCore` so they should always get raised even if the user overrides OnAttachedToLogicalTree` or `OnDetachedFromLogicalTree` and forgets to call the base implementation.

2017-10-14 09:01 UTC, danwalmsley commented on src/Avalonia.Input/MouseDevice.cs
> +            // TODO: Check visibility and enabled state before setting capture.
see https://github.com/AvaloniaUI/Avalonia/issues/1211

2017-10-14 09:01 UTC, danwalmsley approved these changes
LGTM and tested with AS

2017-10-14 09:35 UTC, kekekeks approved these changes

2017-10-14 10:45 UTC, merged