[need feedback] Create ToggleGroup control
AvaloniaUI/Avalonia pull request #1254
Opened 2017-11-01 04:24 UTC by jstevans

This is an early PR for help on next steps -- I saw discussion on #224 that asked for a way to scope groupnames, and it seems like this is what a Control is for. 

I'm not extremely familiar with Avalonia/WPF, so could use some feedback on whether this is a good start, and what I need to do to actually have a usable Control (and how to use it).

Ideally, I believe A ToggleGroup should:

* be able to contain arbitrary other Controls
* only allow at-most one ToggleButton within it to be selected at a time, by unselecting all other ToggleButtons whenever one is selected

2017-11-12 12:52 UTC, grokys requested changes
First of all: sorry for the delay - I've been a bit snowed under recently.

A few small nits regarding getting property names: `nameof` was added after work was started on Avalonia so we don't yet use it everywhere but it's the preferred way of getting a property name as a string.

Regarding the `ToggleGroup` control itself: this isn't really what I was imagining. This will only track direct visual children of the `ToggleGroup` control, which may be enough but my feeling is that a toggle group should instead start a "scope" for all descendant controls.

I think a better way to start off would be to add a [`GroupName`](https://msdn.microsoft.com/en-us/library/system.windows.controls.radiobutton.groupname(v=vs.110).aspx) property like in WPF.

Once that is added, then there should be a way to "scope" these group names. I'd imagine this could probably be done as an attached property; we could use a control as you've done here but to me an attached property such as `ToggleButton.IsGroupScope="true"` would be more similar to other "scope" mechanisms in Avalonia/WPF such as name scopes and focus scopes.

Does that make sense?

2017-11-12 12:52 UTC, grokys commented on src/Avalonia.Controls/Primitives/ToggleButton.cs
> +                IsCheckedPropertyName,
I'd prefer just using `nameof(IsChecked)` here.

2017-11-12 12:52 UTC, grokys commented on src/Avalonia.Controls/ToggleGroup.cs
> +                SelectedItemPropertyName,
Again, use `nameof(SelectedItem)` here.

2018-05-15 05:51 UTC, grokys commented
This does't seem to have had any further activity so closing for now. Thanks anyway @jstevans!

2018-05-15 05:51 UTC, closed without merging

2021-03-21 20:45 UTC, robloo commented
Probably related to the discussion here https://github.com/microsoft/microsoft-ui-xaml/issues/2310.