Added PointerPressed and PointerReleased events to DataGrid header
AvaloniaUI/Avalonia pull request #12595
Opened 2023-08-19 15:50 UTC by ctacke

## What does the pull request do?

Adds the ability to capture pointer/mouse events at the application for the DataGrid header.

## What is the current behavior?

Currently mouse events trigger sorting when sort is enabled, but do nothing when sort is disabled

## What is the updated/expected behavior with this PR?

An event handler can be attached to the pointer events on a header
Example:
```
var column = new DataGridTextColumn
{
    Header = c.Key,
    Binding = new Binding($"Column{i}")
};
column.HeaderPointerReleased += OnHeaderPointerReleased;
dataGrid.Columns.Add(column);
...
private void OnHeaderPointerReleased(object? sender, Avalonia.Input.PointerReleasedEventArgs e)
{
}

```
## How was the solution implemented (if it's not obvious)?

It is obvious

## Checklist

- [ ] Added unit tests (if possible)?
- [ X ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
No breaking changes

## Obsoletions / Deprecations

No obsoletions

## Fixed issues

No issue reported

2023-08-20 07:00 UTC, Artfunkel commented
General observation: in WPF this (and much more) can be achieved with `EventSetter` in a style targeting column headers. I really miss this feature in Avalonia.

2023-08-20 07:01 UTC, TomEdwardsEnscape commented
General observation: in WPF this (and much more) can be achieved with `EventSetter` in a style targeting column headers. I really miss this feature in Avalonia.

2023-08-20 15:04 UTC, ctacke commented
@microsoft-github-policy-service agree

2023-08-22 01:25 UTC, maxkatz6 commented
@timunie yeah, it can be discussed

2023-09-24 02:48 UTC, maxkatz6 approved these changes

2023-10-04 07:58 UTC, maxkatz6 requested changes

2023-10-04 07:58 UTC, maxkatz6 commented on src/Avalonia.Controls.DataGrid/Avalonia.Controls.DataGrid.csproj
> -    <TargetFrameworks>net6.0;netstandard2.0</TargetFrameworks>
It looks like unwanted changes were pushed with the latest rebase

2023-10-23 20:25 UTC, ctacke commented
@dotnet-policy-service agree

2023-10-31 02:50 UTC, maxkatz6 commented on src/Avalonia.Controls.DataGrid/Avalonia.Controls.DataGrid.csproj
> -  <Import Project="..\..\build\DevAnalyzers.props" />
Please revert all changes in this project file. It seems to be a debug changes, not required for this PR.

2023-11-02 20:59 UTC, maxkatz6 approved these changes
LGTM

2023-11-02 21:32 UTC, merged