Make AttachDevTools conditional for Debug builds.
AvaloniaUI/Avalonia pull request #1274
Opened 2017-11-12 15:29 UTC by grokys

In our [templates](https://github.com/AvaloniaUI/AvaloniaVS/blob/677d0e0b137c8952142520557028c29549ee4bb8/src/Templates/AvaloniaApplicationTemplate/App.xaml.cs#L29) we define a `App.AttachDevTools` method which conditionally enables dev tools in debug mode. This PR adds a `[Conditional("DEBUG")]` attribute to the `TopLevel.AttachDevTools` extension method to automatically only enable dev tools in debug builds.

If the user wants to enable dev tools in all builds, they can simply call what `AttachDevTools` calls, i.e. `Avalonia.Diagnostics.DevTools.Attach(control);`.

The aim of this is to make our templates simpler while still providing the most useful behavior.

2017-11-12 17:46 UTC, jkoritzinsky submitted a review, later dismissed
Approved other than nits

2017-11-12 17:46 UTC, jkoritzinsky commented on src/Avalonia.Diagnostics/DevTools.xaml.cs
> +        public static void AttachDevTools(this TopLevel control)
Nit : indentation

2017-11-12 22:40 UTC, kekekeks commented
Please, don't do this. It might be still useful to have dev tools available in release build. We should have additional `AttachDevToolsInDebugBuild` method instead.

2017-11-12 22:41 UTC, kekekeks requested changes
Please, don't do this. It might be still useful to have dev tools available in release build. We should have additional `AttachDevToolsInDebugBuild` method instead.

2017-11-12 22:58 UTC, grokys commented
I did mention this in the description:

> If the user wants to enable dev tools in all builds, they can simply call what AttachDevTools calls, i.e. Avalonia.Diagnostics.DevTools.Attach(control);.

My reasoning was that 90% of the time a user _won't_ want this in release builds, and `this.AttachDevTools()` is a simple wrapper around `DevTools.Attach(control)`.

2017-11-12 23:16 UTC, kekekeks commented
The thing about `Avalonia.Diagnostics.DevTools.Attach` is that it is in an different class and namespace. So it would be really counter-intuitive. Having two methods is better from usable API point of view.

2017-11-13 04:39 UTC, aelij commented
Adding another method that does the same thing just with a different conditional seems a bit redundant. What was so bad about the current way? Just one method in the template leaves the control in the hands of the dev. I don't think it complicates the template that much.

BTW is it possible to create a method that would work for any opened window automatically? (By using some event when a window is created?) Then it would be possible to just call it once in the App class, and it could be surrounded by `#if`. For example:

```csharp
            InitializeLogging();
            AppBuilder.Configure<App>()
                .UsePlatformDetect()
#if DEBUG
                .UseDevTools()
#endif
                .Start<MainWindow>();
```

2017-11-13 11:25 UTC, grokys commented
> What was so bad about the current way?

I dunno, I just don't like having `#if`s in the code if possible, I guess it makes what's happening more obvious, but do you think that most people will want to enable the devtools in release builds?

> BTW is it possible to create a method that would work for any opened window automatically?

Yes, we should try to do this, I agree.

2017-11-14 09:27 UTC, grokys commented
Going to close this as it looks like people don't think it's a great idea.

2017-11-14 09:27 UTC, closed without merging