fix: Potential TransformGroup memory leak
AvaloniaUI/Avalonia pull request #13529
Opened 2023-11-07 16:23 UTC by workgroupengineering

## What does the pull request do?

Subscribe/Unsubscribe of the notification Children change on OnPropertyChanged

## What is the current behavior?

- Subscribe the notification on Children change only `ctor`.
- Unsubscribe of the notification Children change is never made.
- If assing Children property does not unsubscribe of the notification of the change of children.

## What is the updated/expected behavior with this PR?

I subscribe only `PropertyChanged` instead of `CollectionChanged`, because when Add or Remove item `AvaloniaList<T>` notify change of `Count` property.

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

2023-11-07 16:51 UTC, jp2masa commented
> I subscribe only PropertyChanged instead of CollectionChanged, because when Add or Remove item AvaloniaList<T> notify change of Count property.

I don't think this assumption is safe. It may be with the current implementation, but replacing items does not change item count.

2023-11-07 17:04 UTC, workgroupengineering commented
> > I subscribe only PropertyChanged instead of CollectionChanged, because when Add or Remove item AvaloniaList notify change of Count property.
> 
> I don't think this assumption is safe. It may be with the current implementation, but replacing items does not change item count.

Good catch. I incorrectly assumed Avalonia<T> was like `ObservableCollection<T>` which reports [OnIndexerPropertyChanged](https://github.com/dotnet/runtime/blob/85d3773b9316bc4283bd85eb7e0da76b41b19ee8/src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs#L139).

What do you suggest I do?

2023-11-19 09:56 UTC, MrJul requested changes
Thanks for the PR!

For correctness `Transforms` should also override all other methods modifying the list: `RemoveAt()`, `RemoveAll`, `InsertAt`, `InsertRange`, etc.
That's a bit much, we already have the nice `ForEachItem` which handles all that, used previously.

The changes can be simplified to:
 - Keep the `IDisposable` returned by `ForEachItem` in a field.
 - When when the `Children` collection changes:
    - Dispose the old `IDisposable`.
	- Unsubcribe from the items in the old collection.
	- Call `ForEachItem` again on the new collection.

This should handle all cases.

2023-11-20 20:02 UTC, MrJul requested changes
Logic looks good, a couple naming changes left then we're good to go :)

2023-11-20 20:02 UTC, MrJul commented on src/Avalonia.Base/Media/TransformGroup.cs
> +        private readonly EventHandler ChildTransform_Changed_Handler;
Naming: please respect conventions, use something like `_childTransformChangedHandler` or `_onChildTransformChanged`

2023-11-21 11:06 UTC, MrJul approved these changes
LGTM, thanks!

2023-11-21 12:01 UTC, merged