Make IsEffectivelyVisible useful
AvaloniaUI/Avalonia pull request #13972
Opened 2023-12-15 18:20 UTC by jmacato

cc @grokys

2023-12-15 20:55 UTC, jp2masa reviewed
Some method names seem to be wrong: `UpdateIsEffectivelyEnabled`, `SyncIsEffectivelyEnabledFromParent`, it should be `Visible`, not `Enabled`.

Also, I may be reading it wrong, but not sure if the logic always works, e.g. does adding this to the test work?

```cs
child2.IsVisible = false;
root.IsVisible = true;

Assert.False(child2.IsEffectivelyEnabled);
```

Finally, I think there's room for optimization in `UpdateIsEffectivelyEnabled`, so that it only needs to do the recursive call when `child.IsVisible`.

2023-12-16 04:34 UTC, jmacato commented
@jp2masa thanks for the advise! 

>child2.IsVisible = false;
>root.IsVisible = true;
>Assert.False(child2.IsEffectivelyEnabled);

Good catch on this one! I'm adding this to the test now!

> Finally, I think there's room for optimization in UpdateIsEffectivelyEnabled, so that it only needs to do the recursive call when child.IsVisible.

Makes sense

2023-12-16 09:21 UTC, workgroupengineering commented
We could simplify the code this way by avoiding loops.

```c#
        /// <summary>
        /// Gets a value indicating whether this control and all its parents are visible.
        /// </summary>
        public bool IsEffectivelyVisible => 
            IsVisible && (VisualParent?.IsEffectivelyVisible ?? true);
```

2023-12-16 11:26 UTC, jmacato commented
@workgroupengineering we intend to provide internal event updates when IEV changes, so we can't do what you suggested there unfortunately.

2024-01-19 09:02 UTC, grokys requested changes
A few nits, but also this doesn't seem to handle correctly setting the `IsEffectivelyVisible` state when adding a grandchild. Here is a failing test:

```
        [Fact]
        public void Added_Grandchild_Has_Correct_IsEffectivelyVisible()
        {
            var child = new Decorator();
            var grandchild = new Decorator();
            var root = new TestRoot 
            { 
                IsVisible = false,
                Child = child
            };

            child.Child = grandchild;
            Assert.False(grandchild.IsEffectivelyVisible);
        }
```

2024-01-19 09:29 UTC, grokys commented on src/Avalonia.Base/Visual.cs
> +            SyncIsEffectivelyVisible(_visualParent);
Question: should `IsEffectivelyVisible` be set when the `AttachedToVisualTree`/`DetachedFromVisualTree` event is called? My initial thought is "yes", though you may know more than me.

2024-01-19 12:11 UTC, grokys commented
The `VisualExtensions_GetVisualsAt.Should_Find_Control` test seems to be flaky: I've seen it occur on macOS and now the Linux builds, but it passes locally. Not sure if it's caused by this PR or not.

2024-01-23 09:18 UTC, grokys approved these changes

2024-01-23 12:05 UTC, merged