tidy ControlCatalog.cspoj
AvaloniaUI/Avalonia pull request #1487
Opened 2018-04-11 09:19 UTC by danwalmsley

2018-04-12 16:53 UTC, grokys requested changes
While you're at it, could you trim the other unneccesary stuff too? :D

2018-04-12 16:53 UTC, grokys commented on samples/ControlCatalog/ControlCatalog.csproj
>    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
A lot of this stuff can be removed too. We should be basing this on our project template.

2018-04-12 21:36 UTC, danwalmsley commented
Sure do you know which projects are affected?

2018-04-12 21:50 UTC, danwalmsley commented
should be better now, do you know of any other project files that need a clean up?

2018-04-16 23:07 UTC, grokys approved these changes

2018-04-16 23:08 UTC, grokys commented
The other samples could do with being converted to the new csproj format, but we can do that separately.

2018-04-16 23:32 UTC, merged