Constrain CenterOwner window to screen.
AvaloniaUI/Avalonia pull request #14982
Opened 2024-03-14 14:43 UTC by grokys

When a window is opened with `WindowStartupLocation.CenterOwner` it can be opened partially offscreen. This can make it particularly tricky if the title bar is shown offscreen as the user can no longer move the window fully on-screen.

Constrain the window to the current screen when showing in this mode.

This logic is also present in WPF: https://github.com/dotnet/wpf/blob/3880169c020787b7e3383acb3679e5e4d538c602/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L3707-L3711

## Fixed issues

Fixes #2578

2024-03-14 16:06 UTC, Takoooooo approved these changes

2024-03-14 16:13 UTC, MrJul requested changes

2024-03-14 16:14 UTC, MrJul commented
Ah, talk about bad timing! I'm removing it from the queue due to the potential crash added.

2024-03-15 09:39 UTC, grokys commented on src/Avalonia.Controls/Window.cs
> +                        .WithX(MathUtilities.Clamp(childRect.X, constraint.X, constraint.Right - rect.Width))
Good catch! Added a check for that case.

2024-03-15 10:27 UTC, MrJul approved these changes

2024-03-15 11:56 UTC, merged