Minor csproj spring cleaning
AvaloniaUI/Avalonia pull request #1549
Opened 2018-05-04 12:45 UTC by jmacato

- What does the pull request do?
  * Cleaned up all csproj files that can be cleaned.
  * Ported RenderTest and VirtualizationTest to the newer csproj format and to .NET Core

2018-05-06 00:02 UTC, jmacato commented
that makes more sense sir, i was aware of it but i didn't totally understood how it worked

2018-05-06 00:44 UTC, jmacato commented on src/Shared/Shared.props
> +<Project DefaultTargets="Build"
that makes more sense sir, i was aware of it but i didn't totally understood how it worked

2018-05-11 22:54 UTC, grokys requested changes
Hmm, this seems to have broken BindingTest/RenderTest/VirtualizationTest on net 461. I get the following error on running:

```
System.InvalidOperationException: 'No windowing subsystem found. Are you missing assembly references?'
```

I think this is because the Win32 and Direct2D1 libraries need to be referenced under .net fx, as it tries to determine the windowing/rendering subsystems at runtime depending on which libraries are loaded:

https://github.com/AvaloniaUI/Avalonia/blob/ef3afccaa87248dfd38d5e0cc9a83bf36aadfca0/src/Avalonia.DotNetFrameworkRuntime/AppBuilder.cs#L58

2018-05-11 23:05 UTC, grokys commented
Adding the following to the .csproj seems to fix it:

```
  <ItemGroup Condition="'$(TargetFramework)'=='net461'">
    <ProjectReference Include="..\..\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj" />
    <ProjectReference Include="..\..\src\Windows\Avalonia.Direct2D1\Avalonia.Direct2D1.csproj" />
  </ItemGroup>
```

and 

```
  <Import Condition="'$(TargetFramework)'=='net461'" Project="..\..\build\SharpDX.props" />
```

However if I do that I get the error:

```
1>C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error : Cannot find project info for 'D:\projects\AvaloniaUI\Avalonia\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj'. This can indicate a missing project reference.
```

Which seems to be https://github.com/dotnet/sdk/issues/1227

2018-05-11 23:37 UTC, grokys commented
@kekekeks @jkoritzinsky should we still have the difference in the way .net fx and .net core decide which libraries to use? Can't they both use the same logic on both platforms so we don't have to do the conditional project references?

2018-05-12 13:34 UTC, grokys approved these changes
LGTM. I notice that Avalonia.Markup.Xaml hasn't been converted but that's a bit more complicated due to the inclusion of the submodule. Lets do that one separately if possible.

2018-05-12 14:55 UTC, grokys commented
@kekekeks we have a designer test failing on CI:

```
System.TypeLoadException : Unable to find any of types: Avalonia.DesignerSupport.DesignerAssist
      Stack Trace:
        tests\Avalonia.DesignerSupport.Tests\Checker.cs(71,0): at Avalonia.DesignerSupport.Tests.Checker.LookupType(String[] names)
        tests\Avalonia.DesignerSupport.Tests\Checker.cs(76,0): at Avalonia.DesignerSupport.Tests.Checker.LookupStaticMethod(String typeName, String method)
        tests\Avalonia.DesignerSupport.Tests\Checker.cs(30,0): at Avalonia.DesignerSupport.Tests.Checker.DoCheck(String baseAsset, String xamlText)
           at Avalonia.DesignerSupport.Tests.Checker.DoCheck(String baseAsset, String xamlText)
        tests\Avalonia.DesignerSupport.Tests\DesignerSupportTests.cs(29,0): at Avalonia.DesignerSupport.Tests.DesignerSupportTests.DesgignerApiShoudBeOperational(String outputDir, String xamlFile)
```

However this passes locally on my machine. Any ideas?

2018-05-15 04:44 UTC, grokys commented
Ok, I've disabled that test for now. Going to get this merged.

2018-05-15 04:44 UTC, merged

2018-05-15 04:44 UTC, jmacato commented
@grokys thank you sir!

2018-05-15 08:56 UTC, kekekeks commented
This test should be updated to use the new client-server previewer infrastructure anyway, so it's probably fine.