added support for linkbase in avalonia resources generator
AvaloniaUI/Avalonia pull request #16118
Opened 2024-06-25 11:27 UTC by Abdesol

## What does the pull request do?
adds support for `LinkBase` in avalonia resources generator

## What is the current behavior?
Avalonia asset loader is not resolving for `LinkBase`

## What is the updated/expected behavior with this PR?
Using LinkBase to set resources path works

## Fixed issues
Fixes #16056

2024-06-30 15:10 UTC, kekekeks commented
Please, add a test (a resource outside of the test lib with LinkBase + some test that loads it from code should be sufficient).

2024-07-27 13:27 UTC, MrJul requested changes
The current implementation is wrong, see previous comments.

I don't think we should handle `LinkBase` in the task itself.
Let MSBuild expand the recursive globs from `LinkBase` into `Link` instead.

This is what the SDK is doing. We should probably copy this behavior.

Reference: https://github.com/dotnet/sdk/blob/74dafbfb0c0d311595da6fc61d24ca57e6d3f80d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L104-L107

2024-07-27 13:27 UTC, MrJul commented on src/Avalonia.Build.Tasks/GenerateAvaloniaResourcesTask.cs
> +                    : !string.IsNullOrEmpty(linkBase)
This treats `LinkBase` and `Link` the same, which isn't correct. `Link` is a file path whereas `LinkBase` is the path before the directory globs, i.e. a directory path.

2024-07-27 13:27 UTC, MrJul commented on tests/Avalonia.Build.Tasks.UnitTest/GenerateAvaloniaResourcesTaskTest.cs
> +        var expected = "/" + path;
The added test doesn't check the right thing: the expected path should be `/path/to/resources/root.xml`.

2024-09-12 04:59 UTC, maxkatz6 commented
Closing due to inactivity

2024-09-12 04:59 UTC, closed without merging