Add support for locating custom renderers
AvaloniaUI/Avalonia pull request #1631
Opened 2018-05-30 02:39 UTC by nc4rrillo

- What does the pull request do?

Adds support for custom renderers to override the defaults. For context, I'm working on a custom rendering backend for Avalonia (which includes a customized `IRenderer` impl) which I intend to have exist _out of tree_ to allow me to experiment freely.

- What is the current behavior?

`ImmediateRenderer` or `DeferredRenderer` are selected based on `useDeferred` passed to `UseWin32`

- What is the updated/expected behavior with this PR?

A custom renderer can potentially live outside of tree. 

- How was the solution implemented (if it's not obvious)?

Makes `Avalonia.Win32`'s `WindowImpl` try to locate another `IRenderer` before falling back to use either `ImmediateRenderer` or `DeferredRenderer`

The potentially controversial aspect is I made `TransformedBounds` public so that I can access it, I think the `ObsoleteAttribute` on it gives plenty of warning. 

Checklist:

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

2018-05-30 04:35 UTC, Gillibald commented
Not sure if I like this approach of createing a custom renderer. Avalonia has a ServiceLocator and a valid renderer should be registered with it in my opinion instead of your Fun<x,y> approach. I much prefer a factory for this:

```
public interface IRendererFactory
{
IRenderer Create(IRenderRoot root, RendererOptions options);
}
```

2018-05-30 04:54 UTC, nc4rrillo commented
I'm not opposed to that, I was currently just registering the Func, but I could add a factory. Went with the route of least resistance though :).

2018-05-31 03:09 UTC, nc4rrillo commented
@Gillibald How does this look :-)

2018-05-31 06:43 UTC, Gillibald commented
Looks good to me. I wonder if we can introduce a DefaultRendererFactory that returns either Immediate Renderer or Deferred Renderer depending on UseDeferredRendering

2018-05-31 17:50 UTC, grokys requested changes
Looks good! Just a small formatting request.

2018-05-31 17:50 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +            return customRendererFactory != null ? customRendererFactory.Create(root, loop) : Win32Platform.UseDeferredRendering ?
This is a bit hard to read. Could you split it into separate `if` statements?

2018-05-31 17:50 UTC, grokys commented on src/Avalonia.Visuals/Media/DrawingContext.cs
> +        public Matrix CurrentContainerTransform => _currentContainerTransform;
Yeah... How to properly handle this is something we've been debating for like years... I'm fine with this hack for now personally, but we need to work out how we're going to do this properly.

2018-06-04 18:16 UTC, nc4rrillo commented
@grokys This is ready for review again

2018-06-14 17:54 UTC, grokys approved these changes
Thanks @nc4rrillo !

2018-06-14 18:45 UTC, merged