fix: Button should not fire the click event on the space key when it is not active
AvaloniaUI/Avalonia pull request #16619
Opened 2024-08-07 16:19 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

Fixes #16184

2024-08-07 16:48 UTC, workgroupengineering commented
Hi @amwx , when you have time try this PR.

2024-08-11 08:40 UTC, MrJul requested changes
I'm a bit torn here. Child controls are supposed to mark events as handled to avoid special cases in parent controls. Here, doing so with `KeyDown`/`KeyUp` will prevent `TextInput`, so that's not a viable solution.

Since this PR solves a real problem, let's go with the focus check for now. I don't see any immediate issue with it, but that's the kind of change that might break unusual hierarchies. Let's be vigilant for future issues.

2024-08-11 08:40 UTC, MrJul commented on src/Avalonia.Controls/Button.cs
> +                    if (TopLevel.GetTopLevel(this)?.FocusManager?.GetFocusedElement() == this)
Please use `IsFocused` instead of using the `FocusManager` directly.

2024-08-11 08:40 UTC, MrJul commented on src/Avalonia.Controls/Button.cs
> +            if (e.Key == Key.Space && TopLevel.GetTopLevel(this)?.FocusManager?.GetFocusedElement() == this)
Please use `IsFocused` instead of using the `FocusManager` directly.

2024-08-11 08:40 UTC, MrJul commented on src/Avalonia.Controls/Button.cs
> +                    // Handle Space only current focus control
Nit: if possible, use a slightly better comment that explains *why* we're doing this.
For example "_Avoid handling Space if the button isn't focused: a child TextBox might need it for text input_"

2024-08-11 08:40 UTC, MrJul commented on src/Avalonia.Controls/Button.cs
> +            // Handle Space only current focus control
Same as above regarding the comment.

2024-08-16 09:27 UTC, MrJul approved these changes

2024-08-16 10:31 UTC, merged

2024-08-18 15:46 UTC, robloo commented
@workgroupengineering Would `SplitButton` be affected by this issue as well? It handles space in a similar way.