feat: x:Shared
AvaloniaUI/Avalonia pull request #16644
Opened 2024-08-09 13:55 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

Fixes #15518

2024-08-10 03:52 UTC, maxkatz6 commented on src/Avalonia.Base/Controls/ResourceDictionary.cs
> +            => Add(key, new NotSharedDeferredItem(factory));
We have AddDeferred with a factory delegate only because it was first added. For AddNotShared there is no need for that.

2024-08-10 03:54 UTC, maxkatz6 commented
I will take a better look next week. @MrJul might be also interested in reviewing it.

2024-08-11 09:36 UTC, MrJul requested changes
The implementation can be simplified by removing duplicate code, reusing existing types, and having only the dictionary know whether an item is shared or not.

2024-08-11 09:36 UTC, MrJul commented on src/Avalonia.Base/Controls/INotSharedDeferredContent.cs
> +public interface INotSharedDeferredContent: IDeferredContent
While we could use a marker interface internally for the `ResourceDictionary` to use, I don't think it should be public here. Ideally it should only be known by the `ResourceDictionary`. We can then simplify things by reusing the existing `IDeferredContent` implementations.

See other comments for details.

2024-08-11 09:36 UTC, MrJul commented on src/Avalonia.Base/Controls/ResourceDictionary.cs
> +        public void AddNotShared(object key, INotSharedDeferredContent notSharedDeferredContent)
This should take a `IDeferredContent` directly.

We can then wrap it inside the dictionary with a private marker class. A single instance overhead is acceptable here, as we expect most resources to have the default `x:Shared=true`.

2024-08-11 09:36 UTC, MrJul commented on src/Avalonia.Base/Controls/ResourceDictionary.cs
> +        private sealed class NotSharedDeferredItem(Func<IServiceProvider?, object?> factory) : INotSharedDeferredContent
Now unused, should be removed.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AstNodes/XamlNotSharedDeferredContentNode.cs
> +class XamlNotSharedDeferredContentNode : XamlAstNode, IXamlAstValueNode, IXamlAstEmitableNode<IXamlILEmitter, XamlILNodeEmitResult>
This is an almost exact copy of `DeferredContentNode`, except the `_deferredContentCustomization field` being initialized in the constructor. Please delete this and reuse `DeferredContentNode`.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +                    :
Nit: formatting, I don't think we ever have have a single `:` on a line by itself, place it on the line above.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +                    :
Nit: formatting, I don't think we ever have have a single `:` on a line by itself, place it on the line above.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +        bool TryGetSharedDirective(XamlAstConstructableObjectNode co, out (IXamlAstNode Node, bool Value) directive)
Nullability: on `false` return, `directive.Node` will be `null`, which isn't expected by the non-nullable `IXamlAstNode`.

Prefer two parameters `[NotNullWhen(true)] out IXamlAstNode? node` and `out bool value` to better represent the return values.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +                        context?.ReportTransformError("Invalid argument type for x:Shared directive.", node);
Unneeded `?`, `context` is never `null`.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +                    context?.ReportTransformError("Invalid number of arguments for x:Shared directive.", node);
Unneeded `?`, `context` is never `null`.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XSharedTransformer.cs
> +    class AdderSetter : IXamlILOptimizedEmitablePropertySetter, IEquatable<AdderSetter>
Again, this is copied and pasted from `AvaloniaXamlIlDeferredResourceTransformer`. Please delete it and reuse the existing class.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Visitors/NotSharedVisitor.cs
> +class NotSharedVisitor : IXamlAstVisitor
I'm not sure I understand the purpose of having a visitor here - why isn't only `x:Shared` checked only on the immediate children instead? This is what's done in `XSharedTransformer`. Ideally the logic should be the same (and shared) for two places.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs
> +        public static unsafe INotSharedDeferredContent NotSharedDeferredTransformationFactoryV0<T>(
You can delete this. As mentioned in the `ResourceDictionary` comments, we can reuse all the existing methods and types here and simply flag the non-shared resources inside the dictionary itself.

2024-08-11 09:36 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
> +        public IXamlMethod? NotSharedDeferredContentExecutorCustomization { get; set; }
Can be removed, see comments on `ResourceDictionary` and `XamlIRuntimeHelpers`.

2024-08-11 09:36 UTC, MrJul commented on tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XSharedDirectiveTests.cs
> +            Assert.True(ReferenceEquals(implicitSharedInstance1, implicitSharedInstance2));
Nit: you can use `Assert.Same` instead.

2024-08-11 09:36 UTC, MrJul commented on tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XSharedDirectiveTests.cs
> +            Assert.True(!ReferenceEquals(notSharedResource1, notSharedResource2));
Nit: you can use `Assert.NotSame` instead.

2024-08-11 09:40 UTC, MrJul commented
Just a though for discussion:

While the feature is useful, needed, and matches WPF, Avalonia usually uses explicit factory types such as `Template` to represent non-shared contents.

Shouldn't we go the same way here, by specializing `StaticResource` to recognize template resources, instead of having `x:Shared`?

2024-08-11 11:31 UTC, BAndysc commented
> Shouldn't we go the same way here, by specializing `StaticResource` to recognize template resources, instead of having `x:Shared`?

My two cents as an user, while I agree Template is a good replacement, it would be very convenient to have x:Shared when porting WPF code.

2024-08-12 07:57 UTC, workgroupengineering commented
Hi, @MrJul, thanks for the review.
I duplicated the code because I wanted to avoid also doing the PR in XamlX which has very long PR approval times. I marked this PR as draft while waiting to prepare the PR for XamlX and then make the changes here.

2024-08-16 08:38 UTC, MrJul commented on src/Avalonia.Base/Controls/INotSharedDeferredContent.cs
> +public interface INotSharedDeferredContent: IDeferredContent
Now that's it's not used at all in public API, I think you can completely remove it and simply check for `NotSharedDeferredItem` in the `ResourceDictionary` instead.

2024-08-16 08:44 UTC, MrJul requested changes
Thank you for the changes, it's looking way better.
I've left a couple of comments for easily fixed issues. After that it should be good to go :)

2024-08-16 08:44 UTC, MrJul commented on src/Avalonia.Base/Controls/INotSharedDeferredContent.cs
> +internal interface INotSharedDeferredContent: IDeferredContent
Now that's it's not used at all in public API, I think you can completely remove it and simply check for `NotSharedDeferredItem` in the `ResourceDictionary` instead.

2024-08-16 08:44 UTC, MrJul commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
> +                cfg.TypeSystem.GetType("Avalonia.Controls.INotSharedDeferredContent"));
The argument type is now `IDeferredContent`

2024-08-16 09:57 UTC, MrJul approved these changes

2024-08-16 09:57 UTC, MrJul commented
LGTM, thanks!

2024-08-16 13:03 UTC, merged