Fix ghosting artifacts on both Renderers #1687
AvaloniaUI/Avalonia pull request #1697
Opened 2018-06-25 09:13 UTC by jmacato

- What does the pull request do?
  - Fixes the bug as described in #1687; This will unblock #987 for future implementation.
- What is the current behavior?
  - Immediate and Deferred Renderers doesn't clear the scene context in the proper way, hence the bug's manifestation. 

Checklist:

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation
 
Fixes #1687

2018-06-25 22:39 UTC, grokys requested changes

2018-06-25 22:39 UTC, grokys commented on src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
> +                context.PlatformImpl.Clear(Colors.Transparent);
This method is called for every visual in the window, so i don't think this is the right place to be clearing the window!

2018-06-26 01:23 UTC, ncarrillo requested changes

2018-06-27 00:43 UTC, nc4rrillo commented on src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
> +
nit: remove this new line

2018-06-27 05:46 UTC, jmacato commented on src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
> +
Oops, good catch!

2018-06-27 09:37 UTC, nc4rrillo commented
LGTM

2018-07-18 15:58 UTC, nc4rrillo commented
@jmacato For Direct2D the backbuffer currently has a pixel format which ignores the alpha mode. This is why you're seeing white where you should see transparent. 

You need to change `AlphaMode` to `Premultiplied` in `SwapChainRenderTarget`

2018-08-13 17:56 UTC, jkoritzinsky commented
@grokys @nc4rrillo any more requested changes here?

2018-08-13 18:44 UTC, nc4rrillo commented
@jkoritzinsky I think @jmacato told me this was causing input issues. I need to boot back into Windows to check.

2018-08-13 18:45 UTC, ncarrillo approved these changes

2018-09-05 22:21 UTC, merged