[SelectingItemsControl] Search all items with TextSearch on key input, not just realized ones
AvaloniaUI/Avalonia pull request #17506
Opened 2024-11-14 05:58 UTC by jonko0493

## What does the pull request do?
This PR brings the behavior of `SelectingItemControl`s with `VirtualizingPanel` presenters into parity with those controls without virtualizing presenters.

## What is the current behavior?
Currently, `SelectingItemsControl`s with `VirtualizingPanel` item presenters (such as `ComboBox`) do not search the full contents of their boxes with text search, only the currently realized controls. This means that if a `ComboBox` is closed, typing does nothing, and even when opened, it will only jump to items immediately in the popup.

## What is the updated/expected behavior with this PR?
Now, `ComboBox`es and other `SelectingItemsControl`s with virtualizing presenters will have proper `TextSearch` for their entire item sets.

## How was the solution implemented (if it's not obvious)?
The anonymous method that existed in the `SelectingItemsControl` class previously has been moved into a static method in `ItemsPresenter`. It's now used there and in `VirtualizingPanel` to check search their items/children for text search. (Note: I don't know if there is a preferred place for a static method like this; happy to move as appropriate.)

Unit test case was added to an existing test and the test was adapted so that ComboBoxes in tests will use a `VirtualizingStackPanel` like the real controls do to ensure the tests fail without this change.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues
Fixes #12490.

2024-11-14 07:51 UTC, jonko0493 commented
@cla-avalonia agree

2024-11-17 19:57 UTC, jonko0493 commented
Everything was passing prior to me merging master... not sure what changed, could be transient failures?

2024-11-17 21:56 UTC, timunie commented
@jonko0493 don't worry tests are a bit flaky atm

2024-12-22 02:31 UTC, jonko0493 commented
Hi folks! Is there something more I need to do to get this reviewed? It is needed for the application I'm developing and it's been a month since it was opened. Thanks!

2025-01-12 21:40 UTC, jonko0493 commented
@timunie I'm very sorry to ping you, but I'm wondering if there's anything else I need to do to get this reviewed. It's needed to make my project usable and I'd prefer not to take a dependency on the PR package. Please let me know if there's anything I can do!

2025-01-12 21:59 UTC, timunie commented
If you have paid support please ask for priority

2025-01-13 17:43 UTC, jonko0493 commented
@timunie I don't have paid support as we're a tiny open source project, so fair enough, I'll wait my turn. This PR has been open three months -- how long should I expect to wait before getting a review without paid support?

2025-01-14 18:13 UTC, MrJul requested changes
Thank you for your contribution.

While the implementation has its merits, we now have different behaviors for standard panels and for `VirtualizingPanel`.
The non-virtualized implementation searches inside item containers (controls) directly. The new implementation for `VirtualizingPanel` searches only inside `Items`.

We should have the same implementation for both panels here, for consistency.
Looking at WPF, it always searches in `Items`, so I propose that we do the same, whatever the panel.

The search should look for:
 - `TextSearch.Text` (current)
 - `IContentControl.Content.ToString()` (current)
 - `item.ToString()`
 
(Ideally we'd also consider `DisplayMemberBinding`, like WPF does, but this is out of scope of this PR and can be added later).

2025-01-14 21:09 UTC, jonko0493 commented
@MikeCodesDotNET Thanks so much for letting me know and I'm sorry for misrepresenting how long the PR had been open -- that was truly a mistake on my part (I can't do date math well in my head, apparently lol).

@MrJul Thank you for the review! The changes you've suggested make good sense. I'll make them in the next few days.

2025-02-22 17:20 UTC, jonko0493 commented
@MrJul Sorry for the delay -- I am embarrassed that it took so long but life really hit me with a ton of stuff all at once right after I said I was going to do this. In any case, I believe I have addressed your feedback. If you could give this another look when you get a chance, I would greatly appreciate it!

2025-02-26 14:20 UTC, MrJul commented
> @MrJul Sorry for the delay -- I am embarrassed that it took so long but life really hit me with a ton of stuff all at once right after I said I was going to do this.

No worries, life happens and in my opinion should always be the priority! :)
Thank you for coming back to this.

2025-02-26 14:20 UTC, MrJul approved these changes
LGTM, thank you!

2025-02-26 16:26 UTC, merged

2025-02-26 17:32 UTC, jonko0493 commented
@MrJul Thanks so much for your review and help!

2025-12-20 13:19 UTC, DamirLisak commented
Unfortunately, this commit has a minor flaw. For a ComboBox, the TextBox (PART_EditableTextBox) sets `e.Handled` to `true`:

https://github.com/AvaloniaUI/Avalonia/blob/2bd109c808a308fcfb2f3b95103f79164ec4787d/src/Avalonia.Controls/TextBox.cs#L1072

Therefore, this event is **not routed** to the `SelectingItemsControl` and `OnTextInput()` is not called. The only workaround is for the user to derive the ComboBox and to add your own ClassHandler to handle the event:

```
        static MyComboBox()
        {
            // Add class handler to intercept text input even when handled by TextBox
            InputElement.TextInputEvent.AddClassHandler<MyComboBox>(
                (cb, e) => cb.HandleTextInputForSearch(e),
                RoutingStrategies.Bubble,
                handledEventsToo: true);
        }

        private void HandleTextInputForSearch(TextInputEventArgs e)
        {
            if (!IsTextSearchEnabled)
                return;

            if (e.Handled)
                e.Handled = false;
            OnTextInput(e);
        }
```