[TextBox] Add readonly property: LineCount.
AvaloniaUI/Avalonia pull request #17656
Opened 2024-12-01 06:46 UTC by rabbitism

## What does the pull request do?

Port WPF property to Avalonia
https://github.com/dotnet/wpf/blob/a08bc2f79bb45e46257368363b4bff594a0c848c/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBox.cs#L899-L920

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

Some notes about test cases:
The test cases are what I observed from actual running app's behavior. 

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

2024-12-01 11:51 UTC, maxkatz6 commented
Not sure how impactful on perf it would be, but LineCount could be a DirectProperty, supporting change notifications.

2024-12-01 13:17 UTC, rabbitism commented
> Not sure how impactful on perf it would be, but LineCount can be a DirectProperty, supporting change notifications.

TextLayout.TextLines cannot be subscribed, thus we have to report change for every Text change and Bounds change. It can be expensive.

2024-12-15 12:37 UTC, MrJul commented
I'm really surprised that WPF exposes a non-observable property here.
I can already see the bug reports coming in from bindings not working.

If we can't bind it, maybe it should be a method instead?

2024-12-16 07:20 UTC, rabbitism commented
> If we can't bind it, maybe it should be a method instead?

I don't have a preference, please let me know if team get a final decision.

2025-01-02 02:56 UTC, rabbitism commented
Any updates on this?

2025-01-14 18:19 UTC, MrJul commented
Diff for API review:

```diff
 namespace Avalonia.Controls
 {
     public class TextBox
     {
+        public int LineCount { get; }
     }
 }
```

2025-01-14 18:19 UTC, MrJul commented
> Any updates on this?

Sorry for the delay, we'll have an API review soon.

2025-01-21 15:24 UTC, MrJul requested changes
Notes from the API review meeting:

Use a method instead.

Expected API:
```csharp
public class TextBox
{
    public int GetLineCount();
}
```

2025-01-22 09:13 UTC, MrJul approved these changes
LGTM, thank you!

2025-01-22 09:52 UTC, merged