[ScrollViewerPresenter] Fix rtl scroll (#16667)
AvaloniaUI/Avalonia pull request #17714
Opened 2024-12-08 14:04 UTC by ijklam

## What does the pull request do?

Make `ScrollViewerPresenter` horizontal scroll naturally when `FlowDirection` set to `RightToLeft`.

Fix #16667.

## What is the current behavior?

When `FlowDirection` set to `RightToLeft`, swiping from right to left will move the left-hand-side content to the right.

## What is the updated/expected behavior with this PR?

When `FlowDirection` set to `RightToLeft`, swiping from right to left should move the right-hand-side content to the left.

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

Fix #16667.

2024-12-17 11:55 UTC, ijklam commented
@maxkatz6 Any updates?

2025-01-14 18:42 UTC, MrJul requested changes
Thank you for your contribution!
A couple of minor comments and this will be good to merge.

2025-01-14 18:42 UTC, MrJul commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +                var delta = CheckFlowDirection(e.Delta);
This should be done right after the `if` block below, so that `Shift+Wheel Up` correctly scrolls left and `Shift+Wheel Down` correctly scrolls right in RTL mode.

2025-01-14 18:42 UTC, MrJul commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +        private Vector CheckFlowDirection(Vector delta)
Nit: consider removing `Check` from the name, which usually implies a boolean result. (e.g. `AdjustDeltaForFlowDirection`, `GetDirectionDelta` or something better - as always, naming is hard!).

2025-01-16 09:26 UTC, MrJul requested changes

2025-01-16 09:26 UTC, MrJul commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +                    delta = AdjustDeltaForFlowDirection(delta, FlowDirection);
This should be done unconditionally, not in an `else` block. Otherwise, shift + scroll wheel is still reversed.

2025-01-16 10:20 UTC, ijklam commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +                    delta = AdjustDeltaForFlowDirection(delta, FlowDirection);
I am not sure about this. I think shift+scroll should remained the original behavior, as scrolling up means to show later content. Maybe ask some native Arabic speakers' opinion like @Mop1398

2025-01-16 10:39 UTC, MrJul commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +                    delta = AdjustDeltaForFlowDirection(delta, FlowDirection);
Afaict, at least on browsers, shift+wheel up scrolls left even with `direction: rtl`.
But I'm no expert here, let's wait for a native speaker's input.

2025-02-01 14:52 UTC, MrJul commented on src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
> +                    delta = AdjustDeltaForFlowDirection(delta, FlowDirection);
Note: I've searched for, but couldn't find any other behavior than Shift+Left scrolling Up and Shift+Right scrolling Down, whatever the text direction. 

I don't want to hold this PR, as the original issue is fixed. I'm going to merge it. We can revisit the Shift+Left/Right scrolling in another issue if needed.

2025-02-01 14:53 UTC, MrJul approved these changes
LGTM, thank you!

2025-02-01 19:08 UTC, merged