feat: add hidesuggestions property to textbox
AvaloniaUI/Avalonia pull request #17815
Opened 2024-12-21 22:13 UTC by jcsawyer

## What does the pull request do?

Add a `HideSuggestions` property to `TextInputOptions` that when set on a text box, the keyboard does not show the autocomplete/word suggestions above the keyboard on Android/iOS.

## What is the updated/expected behavior with this PR?

Android/iOS keyboards do not present suggestions when the new `HideSuggestions` property is set to `true`.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

## Fixed issues

Fixes #16579

2024-12-21 22:49 UTC, jcsawyer commented
@cla-avalonia agree

2025-01-15 07:59 UTC, MrJul commented
API diff for review:

```diff
 namespace Avalonia.Input.TextInput
 {
     public class TextInputOptions
     {
+        public static readonly AttachedProperty<System.Boolean> HideSuggestionsProperty;
+        public System.Boolean HideSuggestions { get { throw null; } set { } } 
+        public static System.Boolean GetHideSuggestions(StyledElement avaloniaObject) { throw null; }
+        public static void SetHideSuggestions(StyledElement avaloniaObject, System.Boolean value) { }
     }
 }
```

2025-01-21 15:35 UTC, MrJul requested changes
Notes from the API review meeting:

The default behavior varies by platform: suggestions are enabled by default on mobile and disabled on desktop. This requires a default state, with a nullable boolean, and `null` being the default value.

Plus, the negative name isn't ideal, so we chose to go with `ShowSuggestions` instead.

Expected API:

```csharp
public class TextInputOptions
{
    public static readonly AttachedProperty<bool?> ShowSuggestionsProperty;
    public bool? ShowSuggestions { get; set; } 
    public static bool? GetShowSuggestions(StyledElement);
    public static void SetHideSuggestions(StyledElement, bool?);
}
```

2025-01-21 19:14 UTC, jcsawyer commented
API updated according to specified.

2025-01-21 21:02 UTC, MrJul requested changes
A few minor points and this is good to go!

2025-01-21 21:02 UTC, MrJul commented on src/iOS/Avalonia.iOS/TextInputResponder.Properties.cs
> +            _view._options == null ?
This can be simplified to `_view._options?.ShowSuggestions == false ? No : Yes`

2025-01-21 21:02 UTC, MrJul commented on src/iOS/Avalonia.iOS/TextInputResponder.Properties.cs
> +            _view._options == null ?
This can be simplified to `_view._options?.ShowSuggestions == false ? No : Yes`

2025-01-21 21:24 UTC, MrJul approved these changes
LGTM, thank you!

2025-01-22 00:47 UTC, merged