OpenGL-accelerated Skia drawing in Win32/GTK backends
AvaloniaUI/Avalonia pull request #1935
Opened 2018-10-01 10:48 UTC by kekekeks

Differencies from  https://github.com/AvaloniaUI/Avalonia/pull/1917

- While being platform-agnostic allows for calling OpenGL-functions
- Actual implementations for Win32/GTK via EGL/ANGLE
- Proper separation of display, context and surface
- Separate OpenGL-context for UI-thread drawing (RenderTargetBitmap is hw-accelerated)
- No hardcode for stencil size and sample count

2018-10-01 14:40 UTC, jmacato commented
This really is a game-changing code! 

I was testing with RenderDemo & ImmediateRenderer and sometimes it crashes whenever i click on Tabs/Menu. this was the stack trace:
```
WARNING: failed to attach stencil buffer for clip mask. Clip will be ignored.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.Platform.DefaultMenuInteractionHandler.PointerReleased(Object sender, PointerReleasedEventArgs e) in {avaloniaDir}/src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs:line 334
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in {avaloniaDir}/src/Avalonia.Interactivity/Interactive.cs:line 199
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in {avaloniaDir}/src/Avalonia.Interactivity/Interactive.cs:line 158
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in {avaloniaDir}/src/Avalonia.Interactivity/Interactive.cs:line 141
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, IInputRoot root, Point p, MouseButton button, InputModifiers inputModifiers) in {avaloniaDir}/src/Avalonia.Input/MouseDevice.cs:line 247
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in {avaloniaDir}/src/Avalonia.Input/MouseDevice.cs:line 132
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in {avaloniaDir}/src/Avalonia.Input/MouseDevice.cs:line 104
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in {avaloniaDir}/src/Avalonia.Input/InputManager.cs:line 38
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in {avaloniaDir}/src/Avalonia.Controls/TopLevel.cs:line 350
   at Avalonia.Gtk3.WindowBaseImpl.<>c__DisplayClass94_0.<OnInput>b__0() in {avaloniaDir}/src/Gtk/Avalonia.Gtk3/WindowBaseImpl.cs:line 400
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in {avaloniaDir}/src/Avalonia.Base/Threading/JobRunner.cs:line 169
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in {avaloniaDir}/src/Avalonia.Base/Threading/JobRunner.cs:line 40
   at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass28_0.<Signal>b__0() in {avaloniaDir}/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 108
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data) in {avaloniaDir}/src/Gtk/Avalonia.Gtk3/Interop/GlibTimeout.cs:line 12
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken) in {avaloniaDir}/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 81
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in {avaloniaDir}/src/Avalonia.Base/Threading/Dispatcher.cs:line 64
   at Avalonia.Application.Run(Window mainWindow) in {avaloniaDir}/src/Avalonia.Controls/Application.cs:line 259
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in {avaloniaDir}/src/Avalonia.Controls/AppBuilderBase.cs:line 128
   at RenderDemo.App.Main(String[] args) in {avaloniaDir}/samples/RenderDemo/App.xaml.cs:line 19
```

2018-10-01 16:18 UTC, jmacato commented
@kekekeks yeah, it's repeating that warning over and over when the rotating geometry clipped animation is running

2018-10-01 17:02 UTC, danwalmsley requested changes
A few nits, let me know if you want me to do the fixes

2018-10-01 17:56 UTC, kekekeks commented on src/Gtk/Avalonia.Gtk3/ClipboardImpl.cs
> +using Avalonia.Platform.Interop;
Utf8Buffer got moved to that namespace, see https://github.com/AvaloniaUI/Avalonia/pull/1935/commits/add3e8109588d6d88662ef67ab263e7b1f3fd85c

2018-10-01 17:57 UTC, kekekeks commented on src/Avalonia.OpenGL/EglDisplay.cs
> +        class EglContext : IGlContext
Those three are tightly coupled, that's why EglContext and EglSurface are nested classes.

2018-10-01 17:59 UTC, kekekeks commented on src/Avalonia.OpenGL/EglGlPlatformSurface.cs
> +    public class EglGlPlatformSurface : IGlPlatformSurface
I'd prefer to have those in the same file since `EglGlPlatformSurface` is the only user of this interface

2018-10-01 19:15 UTC, danwalmsley commented on src/Avalonia.OpenGL/EglDisplay.cs
> +        class EglContext : IGlContext
oh yeah, missed that, if there nested then that's my mistake :)

2018-10-01 19:15 UTC, danwalmsley commented on src/Gtk/Avalonia.Gtk3/ClipboardImpl.cs
> +using Avalonia.Platform.Interop;
ah ok

2018-10-02 11:50 UTC, danwalmsley commented
I think the only functional change required now is to make it disabled by default, so that we can add this to 0.7 release and people who want to test it can, but existing code wont potentially be exposed to any issues in gpu rendering we don't yet know about.

2018-10-02 12:31 UTC, danwalmsley approved these changes
LGTM great work :)

2018-10-02 12:57 UTC, merged