Fixed TextBox OutOfRangeException
AvaloniaUI/Avalonia pull request #1955
Opened 2018-10-08 20:53 UTC by donandren

- What does the pull request do?
Fixes occasional textbox exceptions issue #1954
- What is the current behavior?
Throws exceptions
- What is the updated/expected behavior with this PR?
Textbox have valid state and don't throw exceptions
- How was the solution implemented (if it's not obvious)?
validate selectionstart and selectionend when text is changed

Checklist:

- [ ] Added unit tests (if possible)?

If the pull request fixes issue(s) list them like this:

Fixes #1954

2018-10-08 20:54 UTC, donandren commented
@grokys @jkoritzinsky this PR should be ready for merge, fixes the issue completely

2018-10-09 20:36 UTC, grokys requested changes
Looks good - just a few tiny nits.

2018-10-09 20:36 UTC, grokys commented on src/Avalonia.Controls/TextBox.cs
> +                    var carretIndex = CaretIndex;
Nit: should be `caretIndex`.

2018-10-09 20:36 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
> +        public void SelectionEnd_Dont_Cause_Exception()
Nit: should be `SelectionEnd_Doesnt_Cause_Exception`

2018-10-09 20:36 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
> +        public void SelectionStart_Dont_Cause_Exception()
Nit: should be `SelectionStart_Doesnt_Cause_Exception`

2018-10-10 20:51 UTC, grokys approved these changes

2018-10-10 21:33 UTC, merged