Viewbox implementation
AvaloniaUI/Avalonia pull request #2066
Opened 2018-11-02 17:12 UTC by donandren

- What does the pull request do?
Add Viewbox and simplifies LayoutTransform control
- What is the current behavior?
we don't have Viewbox
- What is the updated/expected behavior with this PR?

Checklist:

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes

2018-11-10 18:11 UTC, grokys requested changes
I created a [ViewBoxPage](https://gist.github.com/grokys/b11ff7e90257640c3f7b62807e0fc498) for the control catalog and compared it with the same [page in WPF](https://gist.github.com/grokys/8d88d9944f7cebee90c15d3bf5998bef). The results don't look quite right.

WPF looks as I'd expect it to:

![image](https://user-images.githubusercontent.com/1775141/48304578-fc071380-e51b-11e8-9c00-8cf8843a02e6.png)

However, Avalonia doesn't look right:

![image](https://user-images.githubusercontent.com/1775141/48304603-4ee0cb00-e51c-11e8-9bb7-d67cb1493fc1.png)

Not quite sure what's causing the difference. Is this expected?

2018-11-10 20:34 UTC, donandren commented
updated default of ClipToBounds to true (which i missed initially) to behave as wpf.
I think differences in wpf vs. avalonia are not caused by Viewbox itself.
not sure where they are coming from, but

-  GridRowDefinitions with Auto height in a StackPanel definatelly is a complex scenario and could be misleading.
- having Path report it's default bounds might not be working as expected, not sure

anyway made tiny modifications to example page and it look to be it's working fine:
https://gist.github.com/donandren/3105ed68cdb4f7871abf15045ae671bf

2018-11-10 20:34 UTC, donandren commented on src/Avalonia.Controls/ViewBox.cs
> +    public class Viewbox : Decorator
fixed

2018-11-11 10:08 UTC, grokys commented
Yeah, I was wondering if the problem might be with `Grid`. Might be worth investigating this separately... Also could you add the `ViewboxPage` to ControlCatalog? Or I can add it if you'd prefer.

2018-11-19 21:12 UTC, grokys approved these changes
LGTM! Just pushed a quick fix to alphabetically order the pages in ControlCatalog, hope that's OK!

2018-11-19 21:24 UTC, merged