Fix and Unittests for Star Column Width
AvaloniaUI/Avalonia pull request #2139
Opened 2018-11-26 22:46 UTC by donandren

Star Column Width don't work well with dynamic desired size based on availablesize

- What does the pull request do?
- What is the current behavior?
- What is the updated/expected behavior with this PR?
- How was the solution implemented (if it's not obvious)?

Checklist:

- [ ] Added unit tests (if possible)?

If the pull request fixes issue(s) list them like this:

Fixes #2138
Fixes #2129

2019-01-09 21:18 UTC, grokys commented
@walterlv does this look right to you? Any idea of a fix?

2019-01-23 13:40 UTC, grokys commented
Taking a look at these tests I notice 2 things:

- `Layout_LeftAlingment_And_StarColumn_Shouldnt_Stretch` is passing. Should it be failing?
- Comparing `Layout_StarColumn_Should_Pass_Calculated_Width_On_Measure_And_Arrange` with WPF: WPF doesn't measure twice, however it _does_ calculate the fact that due to the columns being `*,*`, 100 pixels is the maximum for each column and passes this to `Measure`

However the outcome is actually the same as WPF: the bounds are correctly set to `0, 50, 100, 100`. So I don't think these tests actually get to the bottom of the problem.

2019-01-25 12:11 UTC, donandren commented
#2261 another failing tests for the same grid problem

2019-01-29 23:41 UTC, walterlv commented
It seems that this is a fittable idea to solve the dynamic desired size issue. I did this too simple.

2019-01-29 23:50 UTC, walterlv requested changes

2019-01-29 23:50 UTC, walterlv commented on tests/Avalonia.Controls.UnitTests/GridTests.cs
> +            Assert.Equal(target.ColumnDefinitions[0].ActualWidth, 100);
The expected argument should be on the left and the actual value should be on the right. So as the below.

2019-06-19 12:52 UTC, grokys commented
Closing this as we've ported `Grid` from WPF now.

2019-06-19 12:52 UTC, closed without merging