Allow for modifying Skia PlatformRenderInterface behavior.
AvaloniaUI/Avalonia pull request #2364
Opened 2019-03-11 12:38 UTC by MarchingCube

## What does the pull request do?

Allows the user to change behavior of Skia rendering platform. I need this for my project as I want to control creation of `GrContext` and render target creation.

## What is the current behavior?

While I can technically change the used rendering platform I cannot just modify a small part of the current `PlatformRenderInterface` without rewriting it from scratch.

## What is the updated/expected behavior with this PR?

User can now override platform behavior.

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

@kekekeks

2019-03-11 18:07 UTC, kekekeks commented
I'm not sure that we want to make these methods to be the part of the public API. I don't know why PlatformRenderInterface class is public to begin with.

It you want to control GrContext and render target creation, I think we should add some kind of extensibility interface. Something like:
```csharp
interface ICustomSkiaGpu
{
      GrContext CreateImmediateUiThreadGrContext();
      ICustomSkiaRenderTarget TryCreateRenderTarget(IEnumerable<object> surfaces);
}
interface ICustomSkiaRenderTarget : IDisposable
{
      ICustomSkiaRenderSession BeginRendering();
}
interface ICustomSkiaRenderSession : IDisposable
{
      GrContext GrContext {get;}
      double ScaleFactor {get;}
      SkCanvas Canvas {get;}
}
```

Also see https://github.com/AvaloniaUI/Avalonia/issues/2365 I think it should be specified by
```
    .With(new SkiaOptions { CustomGpuFactory = () => new MyCustomGpu() });
```

2019-03-11 18:07 UTC, kekekeks requested changes
^

2019-03-12 17:33 UTC, MarchingCube commented
@kekekeks I thought about this approach but then I noticed that some parts of Skia are public so I figured I can do it with lower effort :)

I have few questions about your design:
- why would we have multiple `GrContext` as implied by `ImmediateUiThreadGrContext` ?
- who is responsible for calling `ICustomSkiaRenderTarget .BeginRendering`? Should I implement some proxy `CustomRenderTarget` that implements `IRenderTarget` and adapts that interface?

2019-03-12 19:24 UTC, kekekeks commented
Currently we have 2 OpenGL contexts with shared resources, one is used for UI thread rendering (for RenderTargetBitmap basically), another one is used by render thread for actual rendering the render targets. Those need to be wrapped into different GrContext objects (right now we are reusing a single one, I *think*, which isn't a good thing but currently doesn't cause issues in most cases since RenderTargetBitmap usage is rare.

2019-03-12 19:25 UTC, kekekeks commented
>who is responsible for calling ICustomSkiaRenderTarget .BeginRendering? Should I implement some proxy CustomRenderTarget that implements IRenderTarget and adapts that interface?

Yes, something like that. See `GlRenderTarget`

2019-03-12 19:44 UTC, MarchingCube commented
Thanks for info. I also forgot to ask how is `ScaleFactor` supposed to be used, who provides that?

2019-03-13 06:34 UTC, kekekeks commented
It represents the DPI of the target surface.

2019-03-13 09:50 UTC, MarchingCube commented
@kekekeks Implemented your feedback, I can cleanup this code later if you are fine with this implementation.

Additionally I am trying to figure what should be the public API of the `Avalonia.Skia` assembly?

I would need some way of getting `SKCanvas` to draw to (using the https://github.com/AvaloniaUI/Avalonia/pull/2185), as I have some custom `SKSurface` that I would like to draw to the `SKCanvas`. Since to actually implement something drawable from Skia I need to implement `IDrawableBitmapImpl` which is internal to the Skia assembly.

2019-03-13 10:05 UTC, Gillibald commented
Isn't it possible to work with an IBitmap implementation if you need access to the SKCanvas(SKSurface)?

2019-03-13 11:34 UTC, MarchingCube commented
You need `IDrawableBitmapImpl` to actually make it work with Skia. Which is an internal interface.

2019-03-13 13:39 UTC, Gillibald commented
I think we should introduce a abstract base class for this and also use SKImage by default when it is possible. Only WritableBitmapImpl needs to use SKBitmap if I am not mistaken.

```
public abstract class BitmapImpl : IBitmapImpl
{
    public abstract SKImage GetSkiaImage();
}
```

2019-03-13 13:53 UTC, MarchingCube commented
For me I actually have `SKSurface` and not an `SKImage`. I could snapshot the surface to an image but that might cause unwanted copy. Since ideally I would like to have gpu -> gpu copy. I will take a look at the API to see what could be abstracted.

2019-03-13 14:07 UTC, Gillibald commented
When you create your surface on GPU Snapshot should also result on GPU

2019-03-13 20:46 UTC, MarchingCube commented
@kekekeks Are you fine with this implementation? I also did some cleanup on Skia image classes, and made more classes internal so it is clearer what should be used from the outside. If you are fine I will add comments and clean it up a bit.

2019-03-13 20:47 UTC, MarchingCube commented on src/Skia/Avalonia.Skia/ImageBitmapImpl.cs
> +    public readonly struct OptionalDispose<T> : IDisposable where T : IDisposable
This will be shared with D2D as it has the same struct.

2019-03-14 14:26 UTC, MarchingCube commented
@kekekeks I trimmed down this PR to just custom gpu changes for now. Let me know if you want more changes.

2019-04-08 08:31 UTC, kekekeks commented
This needs to be refactored to use new "options" way of configuring platforms - https://github.com/AvaloniaUI/Avalonia/pull/2368

2019-04-08 12:51 UTC, MarchingCube commented
@kekekeks Implemented platform options. Let me know if you need more changes in this PR.

2019-04-08 13:49 UTC, kekekeks approved these changes

2019-04-08 14:04 UTC, kekekeks commented
Whoops, not approving. Options are implemented in a wrong way

2019-04-08 14:05 UTC, kekekeks requested changes
Platform options have to be registered with `.With` call on AppBuilder and consumed by Initialize like this: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11Platform.cs#L105

2019-04-08 15:46 UTC, MarchingCube commented
@kekekeks Can you be a bit more specific? My implementation looks the same as Win32 and X11 ones unless I am missing something.

2019-04-08 16:03 UTC, kekekeks commented
I've misinterpreted the code because of this: https://github.com/AvaloniaUI/Avalonia/pull/2364/files#diff-82af421f9bf2b29fd90e5f6c8823dcafR16. Sorry, a bit sick today. 

Will merge once CI passes (Mono has segfaulted on Avalonia.Visuals tests

2019-04-08 16:04 UTC, kekekeks approved these changes

2019-04-08 21:59 UTC, MarchingCube commented
@grokys @kekekeks No idea why CI is failing, seems that a lot of other PRs also have this segfault issue on Linux.

2019-04-12 14:42 UTC, merged