Add NuGet metadata to Directory.Build.props
AvaloniaUI/Avalonia pull request #2816
Opened 2019-08-07 12:29 UTC by worldbeater

### What does the pull request do?

The goal of this PR is to include some metadata into each Avalonia NuGet package. The metadata includes package description, project logo, licensing information, tags. This will improve the look of the Avalonia page on NuGet. 

### What is the current behavior?

Currently, [Avalonia NuGet page](https://www.nuget.org/packages/Avalonia/) has no description and no image.

### What is the updated/expected behavior with this PR?

Now Avalonia NuGet page should include the description, logo and other metadata.

### How was the solution implemented?

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

The changes from this PR should work if the `Directory.build.props` file is included into each project in the solution and the included properties are not overwritten elsewhere. I know Avalonia uses a lot of `*.build.props`  files and also the [Numerge](https://github.com/kekekeks/Numerge) utility, so need a review from experts in Avalonia packaging details. Thanks in advance!

2019-08-08 10:37 UTC, lindexi requested changes

2019-08-08 10:37 UTC, lindexi commented on src/Directory.Build.props
> +    <PackageProjectUrl>http://avaloniaui.net</PackageProjectUrl>
```suggestion
    <PackageProjectUrl>https://avaloniaui.net</PackageProjectUrl>
```

2019-08-08 10:37 UTC, lindexi commented on src/Directory.Build.props
> +    <PackageDescription>A multi-platform .NET UI framework. Avalonia supports Windows, Linux and OSX with experimental mobile support for Android and iOS. Avalonia uses a XAML dialect that should fee
may be can copy from readme

Avalonia is a WPF/UWP-inspired cross-platform XAML-based UI framework providing a flexible styling system and supporting a wide range of Operating Systems such as Windows (.NET Framework, .NET Core), Linux (via Xorg), MacOS and with experimental support for Android and iOS.

2019-08-15 02:13 UTC, lindexi approved these changes

2019-08-15 05:07 UTC, kekekeks commented
>warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [D:\a\1\s\packages\Avalonia\Avalonia.csproj]
>##[error]Process 'MSBuild.exe' exited with code 1.

2019-08-18 15:41 UTC, kekekeks commented
`error NU5035: The PackageLicenseUrl is being deprecated and cannot be used in conjunction with the PackageLicenseFile or PackageLicenseExpression.`

2019-08-18 15:43 UTC, kekekeks commented
https://github.com/AvaloniaUI/Avalonia/blob/b18a2075967a921397b0bf5b96323bcb98f60900/build/SharedVersion.props

2019-09-09 08:38 UTC, merged