Animations subsystem perf fixes.
AvaloniaUI/Avalonia pull request #2895
Opened 2019-08-28 06:07 UTC by jmacato

Related to #2894

2019-08-28 06:22 UTC, kekekeks commented
Are you sure that it won't break transition initialization from XAML? I think need a proper way of lazy initialization instead.

2019-08-28 06:26 UTC, jmacato commented
@kekekeks All transitions from ControlCatalog are done on XAML and it works. But we need a better way of doing lazy init just as you said.

2019-08-28 06:26 UTC, jmacato commented
@MarchingCube Can you do another object count pass on this? I don't have any profiling tools at hand right now.

2019-08-28 15:27 UTC, MarchingCube commented
@jmacato Will take a look today, a bit busy with other stuff at the moment.

2019-08-28 22:21 UTC, MarchingCube commented
After this change after going through all pages in ControlCatalog I only have 1 instance of `Transitions` alive.

I wonder what kind of API we want to provide here, since in UWP `Transitions` is lazy as well and you will never get null. And in Avalonia you can get null.

2019-08-29 02:58 UTC, jmacato commented
@MarchingCube hmm nothing will consume the `Transitions` property of `Animatables` other than the animations subsystem nor would it make sense for other code to do so im not much worried about transitions being null 99% of the time honestly.  We need to fix `AvaloniaPropertyRegistry` to not call getters prematurely just as @kekekeks said.

2019-09-08 17:53 UTC, MarchingCube requested changes
This is going in the right direction, my concern would in the API as after your changes control will have `null` transitions and this is different than UWP (which always returns something).

2019-09-08 17:53 UTC, MarchingCube commented on src/Avalonia.Animation/Animatable.cs
> +            var match = Transitions.FirstOrDefault(x => x.Property == e.Property);
This line is responsible for like 90% `Func` allocations when launching ControlCatalog and it gets worse when you start clicking around. We should "UnLINQ" it.

![image](https://user-images.githubusercontent.com/2588062/64492203-f41a1c00-d271-11e9-8003-482339a9adfd.png)

2019-09-08 18:10 UTC, MarchingCube submitted a review, later dismissed
LGTM

2019-09-08 18:49 UTC, MarchingCube requested changes
Rerun my memory check in dotMemory. Only one `Transitions` object is allocated, and extra LINQ allocations are gone as well 👍

2019-09-08 18:49 UTC, MarchingCube commented on tests/Avalonia.Animation.UnitTests/TransitionsTests.cs
> +                    Transitions =
I guess changes here can be reverted?

2019-09-08 18:49 UTC, MarchingCube commented on src/Avalonia.Animation/Animatable.cs
> +        private bool _isTransitionsSet = false;
Not needed.

2019-09-09 08:17 UTC, merged

2019-09-18 15:19 UTC, yatli commented
@MarchingCube this patch breaks my animation code. The workaround is to trigger the getter immediately after the transition is being set:

```C#
        this.Transitions = transitions;
        this.Transitions; // trigger
```

2019-09-18 15:27 UTC, yatli commented on src/Avalonia.Animation/Animatable.cs
> +            if (_transitions is null || _previousTransitions is null || e.Priority == BindingPriority.Animation) return;
maybe:
`if ((_transitions is null &&_previousTransitions is null) || e.Priority == BindingPriority.Animation) return;`