macOS: Fix title not showing up in SelectFolderDialog, OpenFileDialog and SaveFileDialog
AvaloniaUI/Avalonia pull request #3819
Opened 2020-04-23 22:10 UTC by ElMostafaIdrassi

## What does the pull request do?
This pull request makes it so that the `title` of `SelectFolderDialogs`, `OpenFileDialogs `and `SaveFileDialogs `shows up above the `Save As` text.

![image](https://user-images.githubusercontent.com/25257376/80154223-aeb32080-85ae-11ea-945b-24962e3f9dda.png)

## What is the current behavior?
Currently, the title does not show up in either `SelectFolderDialogs`, `OpenFileDialogs ` or `SaveFileDialogs`.

![image](https://user-images.githubusercontent.com/25257376/80154246-bc68a600-85ae-11ea-9439-78914db68d37.png)

## What is the updated/expected behavior with this PR?
The title is showing up as expected.

## How was the solution implemented (if it's not obvious)?
This was accomplished by setting the `title` in the `message` property in addition to the `title` property of `NSOpenPanel` and `NSSavePanel`.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
None.

## Fixed issues
Fixes first part of #3809 .

2020-04-23 22:11 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=3819) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=3819) before we can accept your contribution.<br/><br/>:x: ElMostafaIdrassi [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=3819)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=3819) it.</sub>

2020-04-23 22:43 UTC, danwalmsley commented on native/Avalonia.Native/src/OSX/SystemDialogs.mm
> +				panel.message = [NSString stringWithUTF8String:title];
please use 4 spaces instead of tabs.

2020-04-23 22:44 UTC, danwalmsley requested changes
just some minor nits.

2020-04-23 23:22 UTC, ElMostafaIdrassi commented
Should be good now.

2020-04-24 08:49 UTC, kekekeks approved these changes

2020-04-24 08:53 UTC, merged