Feature/fluent combobox
AvaloniaUI/Avalonia pull request #4019
Opened 2020-05-28 21:38 UTC by danwalmsley

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

2020-05-29 23:50 UTC, maxkatz6 reviewed
Something wrong with vertical text alignment in ComboBoxItem.

![image](https://user-images.githubusercontent.com/3163374/83313690-4c6cc180-a1e5-11ea-873a-45d891e7677f.png)

2020-05-29 23:50 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/ComboBox.xaml
> +                                Items="{TemplateBinding Items}"
I think there is missed Margin. It exists in [WinUI's style](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ComboBox/ComboBox_themeresources.xaml#L695) and has value "0,4,0,4".
```suggestion
                                Items="{TemplateBinding Items}"
                                Margin="{DynamicResource ComboBoxDropdownContentMargin}"
```

2020-05-30 00:14 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/ComboBoxItem.xaml
> +    <Setter Property="Padding" Value="{DynamicResource ComboBoxItemThemePadding}" />
Interesting moment. I noticed some margin or border between ComboBoxItems in WinUI, but couldn't found it in the [style](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ComboBox/ComboBox_themeresources.xaml#L705). With devtools I found that there is actually border, which is sets in generic.xaml and is not overridden by WinUI. Resources (they are missed in Avalonia in master):
```xaml
<StaticResource x:Key="ComboBoxItemRevealBorderBrush" ResourceKey="SystemControlTransparentRevealBorderBrush" />
<Thickness x:Key="ComboBoxItemRevealBorderThemeThickness">1</Thickness>
```
```suggestion
    <Setter Property="Padding" Value="{DynamicResource ComboBoxItemThemePadding}" />
    <Setter Property="BorderBrush" Value="{ThemeResource ComboBoxItemRevealBorderBrush}" />
    <Setter Property="BorderThickness" Value="{ThemeResource ComboBoxItemRevealBorderThemeThickness}" />
```

2020-05-30 00:18 UTC, maxkatz6 commented
Except issue with alignment and diffs with border and margin, there is one difference in popup behavior: UWP/WinUI popup opens on top of ComboBox with specific offset, while Popup in Avalonia always shows on bottom. 
From other hand, ComboBox in Avalonia feels better because it doesn't change size of ComboBox, when Popup is open moving everything around.

![combobox](https://user-images.githubusercontent.com/3163374/83314183-42e45900-a1e7-11ea-8c62-3d3943083481.gif)

2020-05-30 00:20 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/ComboBoxItem.xaml
> +    <Setter Property="Padding" Value="{DynamicResource ComboBoxItemThemePadding}" />
For another controls we also should look at both styles - from generic.xaml and from WinUI, to combine setters from them.

2020-05-30 13:04 UTC, maxkatz6 requested changes
@danwalmsley 
Resources is missed
```xaml
<StaticResource x:Key="ComboBoxItemRevealBorderBrush" ResourceKey="SystemControlTransparentRevealBorderBrush" />
<Thickness x:Key="ComboBoxItemRevealBorderThemeThickness">1</Thickness>
```

2020-05-30 14:40 UTC, danwalmsley commented
@maxkatz6 seems to be part of reveal resources? https://github.com/microsoft/microsoft-ui-xaml/blob/264f679ae49af3448a84fce75d03e3e838c0a0d5/dev/Materials/Reveal/RevealBrush_rs1_themeresources.xaml 

we can add those when we get reveal in future.

2020-05-30 14:41 UTC, merged

2020-05-30 15:11 UTC, maxkatz6 commented
@danwalmsley 
Yes, part of reveal (without actual reveal in that case). But they are used with commit
https://github.com/AvaloniaUI/Avalonia/pull/4019/commits/2d9b0c6b439c233e4d46198347d9f0f45b8b630e
So it should be runtime error, isn't it?