Add content presenters fluent textbox
AvaloniaUI/Avalonia pull request #4422
Opened 2020-08-01 01:33 UTC by jmacato

## What does the pull request do?
Implements a content hosting for the left and right sides of the fluent TextBox.. Useful for applications like password hide button, etc etc.

![image](https://user-images.githubusercontent.com/16554748/89091172-0d700d80-d3da-11ea-9268-fc7f2a13d8b3.png)

2020-08-01 01:47 UTC, maxkatz6 commented
I see it would be really useful to improve [NumericUpDown](https://github.com/AvaloniaUI/Avalonia/issues/4039#issuecomment-644134993) and [AutoCompleteBox](https://github.com/AvaloniaUI/Avalonia/issues/4023) controls. Thanks!
But I am thinking about default behavior for TextBox - shouldn't it contain ["clear"](https://github.com/AvaloniaUI/Avalonia/issues/4022) and "show password" (in passwordbox mode) buttons out of box?
If yes, should it be placed as "InnerRightContent"?

2020-08-01 01:50 UTC, jmacato commented
@maxkatz6 yep, @danwalmsley suggested the same :D

2020-08-01 12:57 UTC, danwalmsley requested changes
A huge amount of unrelated formatting changes makes it very hard to see the wood for the trees.

The hide/show password needs to be integrated to a button or style that applies that button.

Follow the fluent icons style too.

2020-08-01 12:57 UTC, danwalmsley commented on samples/ControlCatalog/Pages/TextBoxPage.xaml
> +        <TextBox Width="200" Watermark="Floating Watermark" UseFloatingWatermark="True" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit."/>
We need to remove unrelated formatting changes.

2020-08-01 12:57 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +            ShowPasswordProperty.Changed.Subscribe((x)=>
noting happening here?

2020-08-01 12:57 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +                }
unrelated change

2020-08-01 12:57 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +
whitespace...

use => for get / set.

2020-08-01 12:57 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +                    var didClickInSelection = SelectionStart != SelectionEnd &&
?

2020-08-01 23:22 UTC, danwalmsley requested changes

2020-08-12 13:29 UTC, danwalmsley requested changes

2020-08-12 13:29 UTC, danwalmsley commented on src/Avalonia.Controls/Presenters/TextPresenter.cs
> +            AffectsMeasure<TextPresenter>(TextProperty, PasswordCharProperty, ShowPasswordTextProperty,
Why affects measure? id have thought affectsrender?

2020-08-12 13:29 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +        public static readonly StyledProperty<bool> ShowPasswordTextProperty =
Rename to RevealPassword?

2020-08-12 13:29 UTC, danwalmsley commented on src/Avalonia.Controls/TextBox.cs
> +                    var didClickInSelection = SelectionStart != SelectionEnd &&
unrelated change

2020-08-12 13:29 UTC, danwalmsley commented on src/Avalonia.Themes.Fluent/TextBox.xaml
> +    <DrawingGroup x:Key="eye_show_regular">
iv not seen any other resources named with this style.

2020-08-12 13:29 UTC, danwalmsley commented on src/Avalonia.Themes.Fluent/TextBox.xaml
> +  <Style Selector="TextBox.leftClearButton">
imo i think we only need the right hand one.

2020-08-12 13:41 UTC, danwalmsley approved these changes
LGTM

Styling of buttons will be improved by @maxkatz6

2020-08-12 13:43 UTC, danwalmsley requested changes
Please add support for default template.

2020-08-12 14:44 UTC, Gillibald commented
Any reason why there is no PasswordBox that covers all this? The current implementation isn't secure and I don't see why a TextPresenter should have functionality specific to a PasswordBox. I don't think we can support those PasswordBox related properties forever. Just my two cents.

2020-08-12 15:04 UTC, jmacato commented
@Gillibald we should do it in another PR.. but right now there isnt any secure memory handling for passwords in dotnet core.. SecureString is a huge farce and deprecated... One way to do it is to have a special memory zero'ing logic and pinning to prevent GC from copying it somewhere or whatever.

2020-08-12 15:44 UTC, danwalmsley commented
> @Gillibald Right now there isnt any secure memory handling for passwords in dotnet core.. SecureString is a huge farce and deprecated... One way to do it is to have a special memory zero'ing logic and pinning to prevent GC from copying it somewhere or whatever.
> 
> But i agree with textpresenter not doing this password logic and we could address that in another PR

We had that discussion about passwordbox a long time ago. It was decided to just do this simple password char thing with textbox, which IIRC matches winforms.

2020-08-13 17:55 UTC, maxkatz6 requested changes

2020-08-13 17:55 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/TextBox.xaml
> +                            FontSize="{DynamicResource FontSizeSmall}"
FontSizeSmall is missed in Fluent theme. You need to replace it with ControlContentThemeFontSize (there is not "small" equivalent) or restore "TemplateBinding FontSize" as it was before that PR. 
```suggestion
                            FontSize="{TemplateBinding FontSize}"
```

2020-08-13 19:23 UTC, maxkatz6 requested changes

2020-08-13 19:23 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/TextBox.xaml
>      <Setter Property="Cursor" Value="IBeam" />
Cursor=IBeam should be set only on inner DockPanel (there are two of them in the template), so InnerLeft and InnerRight will have default cursor.

2020-08-14 02:20 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/TextBox.xaml
> +                            FontSize="{DynamicResource FontSizeSmall}"
Fixed in https://github.com/AvaloniaUI/Avalonia/pull/4487

2020-08-14 02:20 UTC, maxkatz6 commented on src/Avalonia.Themes.Fluent/TextBox.xaml
>      <Setter Property="Cursor" Value="IBeam" />
Fixed in https://github.com/AvaloniaUI/Avalonia/pull/4487

2020-08-14 09:18 UTC, danwalmsley approved these changes
LGTM, would like an approval from @grokys  before merging... perhaps we should be registering contentpresenters.

2020-08-14 09:41 UTC, merged