Passing dependencies to Application via constructor.
AvaloniaUI/Avalonia pull request #4514
Opened 2020-08-19 09:59 UTC by kiminuo

## What does the pull request do?

Attempts to allow passing dependencies to applications without using `static` fields.

**This is a draft PR for the sake of starting discussion about this topic.**

## What is the current behavior?

`TApp` is always created using parameter-less constructor.

## What is the updated/expected behavior with this PR?

User can specify her own `TApp` factory function so that `TApp` can receive all dependencies through a constructor.

## How was the solution implemented (if it's not obvious)?

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

I think it should not break any existing code.

## Fixed issues

None.

2020-08-19 09:59 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4514) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4514) before we can accept your contribution.<br/><br/>:x: kiminuo [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4514)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=4514) it.</sub>

2020-08-19 10:24 UTC, danwalmsley requested changes
Please remove all the unrealted changed and formatting... so the diff only shows the functional changes for the new api.

2020-08-19 10:29 UTC, kiminuo commented
@danwalmsley Better now?

2020-08-19 22:03 UTC, danwalmsley requested changes
couple of minor nits.

Looks good, will get @grokys or @kekekeks to give some input also.

2020-08-19 22:03 UTC, danwalmsley commented on tests/Avalonia.Controls.UnitTests/AppBuilderTests.cs
> +            public AppWithDependencies()
you can have `private AppWithDependencies ()` here rather than an exception... this makes it impossible for anyone to call the default ctor.

2020-08-19 22:03 UTC, danwalmsley commented on tests/Avalonia.Controls.UnitTests/AppBuilderTests.cs
> +            public object DependencyA { get; }
nit: missing newline after }

2020-08-20 09:41 UTC, danwalmsley approved these changes
LGTM

2020-08-20 10:06 UTC, workgroupengineering commented
Please consider adding documentation at https://github.com/AvaloniaUI/Avaloniaui.net.

2020-08-20 10:06 UTC, grokys approved these changes
I think this makes sense, though I'd wait for @kekekeks' approval as he designed the app lifetimes stuff.

2020-08-20 18:36 UTC, danwalmsley commented
@kekekeks gave this the thumbs up!

2020-08-20 20:47 UTC, merged