[WIP] Feature/fluent datagrid
AvaloniaUI/Avalonia pull request #4534
Opened 2020-08-21 04:50 UTC by maxkatz6

## What does the pull request do?

![gif](https://user-images.githubusercontent.com/3163374/90853502-4d2a7500-e348-11ea-840f-433bd8fdca47.gif)

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

2020-08-24 00:28 UTC, maxkatz6 commented
@danwalmsley Fluent DataGrid uses named StaticResources that aren't updated after user changed theme. Probably it should be filled as a bug, that will be fixed with ThemeDictionaries or equivalent.

2020-08-24 05:47 UTC, maxkatz6 commented
TODO:
- [ ] Header GridLines doesn't work as expected
- [ ] DataGridRowHeader doesn't handle Row:pointerover
- [ ] For some reason Horizontal ScrollBar is visible, when it shouldn't
- [ ] Probably we should rename named static resourced used in DataGrid, make them more consistent

2020-08-25 07:59 UTC, maxkatz6 commented
@danwalmsley ready to review

2020-08-25 20:18 UTC, danwalmsley requested changes
some left over commented code... however yet again another impressive PR ... good job! :)

2020-08-25 20:18 UTC, danwalmsley commented on src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
> +            <!--<DataGridColumnHeader Name="PART_TopRightCornerHeader"
remove commented code?

2020-08-25 20:55 UTC, danwalmsley approved these changes
LGTM

2020-08-25 20:56 UTC, merged

2020-08-28 04:34 UTC, grokys commented
@maxkatz6 I notice that this causes DevTools to display ugly black lines between columns:

Seems to be because the default theme defines:

```
<Setter Property="GridLinesVisibility" Value="Vertical" />
```

I'm guessing that grid lines were buggy before and so didn't work. The fluent theme sets this value to `None` - should we do that for the default theme too do you think?

2020-08-28 05:08 UTC, maxkatz6 commented
@grokys yes, grid lines used undefined brushes before. It was fixed with previous PR - https://github.com/AvaloniaUI/Avalonia/pull/4502/files#diff-c0b1938e2fc3f58e1ceda4a920cbd913L199-R201

Fluent theme has None because WCT has same value. And it looks good as for me.
Default theme with lines looks old-school for a bit though, especially with alternate row colors.

It's easy to change. I can create PR tomorrow if it will be better.

2020-08-28 06:18 UTC, grokys commented
Already done ;) https://github.com/AvaloniaUI/Avalonia/pull/4572