Fiexes issue #4657
AvaloniaUI/Avalonia pull request #4764
Opened 2020-09-28 16:14 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues
Fixes #4657

2020-09-28 17:13 UTC, danwalmsley commented
@workgroupengineering hey, how do we contact you outside of github? your doing a lot of great PRs and we would like to open up a channel of communication with you.. and github is a bit slow for that.

2020-09-28 17:55 UTC, maxkatz6 requested changes

2020-09-28 17:55 UTC, maxkatz6 commented on src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml
> +    <Style Selector="ContextMenu">
Can you use more specific selector?
Maybe something like "DataGrid ContextMenu"

2020-10-05 07:20 UTC, workgroupengineering commented
> 
> 
> @workgroupengineering hey, how do we contact you outside of github? your doing a lot of great PRs and we would like to open up a channel of communication with you.. and github is a bit slow for that.

Hi @danwalmsley ,
this message had escaped me.

I would like it, only my english is really bad.

2020-10-05 13:22 UTC, grokys commented
@workgroupengineering any idea why the context menu foreground is wrong in the devtools? Seems strange that we'd need to fix this in this manner.

2020-10-05 13:40 UTC, grokys commented
> Hi @danwalmsley , this message had escaped me. I would like it, only my english is really bad.

@workgroupengineering that's no problem, but if we could talk about these features before you implement them, we may save everyone a lot of time ;)

Please, contact one of us on gitter and we'll try to set up a space where we can talk about your features!

2020-10-05 14:27 UTC, workgroupengineering commented
> 
> 
> @workgroupengineering any idea why the context menu foreground is wrong in the devtools? Seems strange that we'd need to fix this in this manner.

probably by inheriting the color of the text from the main app theme.

2020-12-02 23:21 UTC, maxkatz6 approved these changes

2020-12-09 21:57 UTC, merged