Fixes/4781 treeview setting bound selected item null
AvaloniaUI/Avalonia pull request #4785
Opened 2020-10-01 09:46 UTC by danwalmsley

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

2020-10-01 16:20 UTC, grokys requested changes

2020-10-01 16:20 UTC, grokys commented on src/Avalonia.Controls/TreeView.cs
> -            if (SelectedItem == null && !_syncingSelectedItems)
I don't think removing this check is correct. Elsewhere, if you have a multi-selecting control and select one item followed by another then `SelectedItem` remains as the first selected item, i.e. `SelectedItem` represents the first selected item in a multi-selection and not the last. I think this is the case in WPF as well.

2020-10-01 16:20 UTC, grokys commented on src/Avalonia.Controls/TreeView.cs
> -            if (SelectedItem == null && !_syncingSelectedItems)
I think the solution would be to surround the whole of `SelectSingleItem` in a `_syncingSelectedItems` fence and manually `SetAndRaise` the `SelectedItem` property.

2020-10-01 16:21 UTC, grokys commented on src/Avalonia.Controls/TreeView.cs
> -            if (SelectedItem == null && !_syncingSelectedItems)
Which would also mean the `_syncingSelectedItems` fence in `SelectedItem.set` is unnecessary.

2020-10-04 13:26 UTC, grokys requested changes

2020-10-04 13:26 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
> +            private int _counter;
`_counter` is unused.

2020-10-04 13:26 UTC, grokys commented on src/Avalonia.Controls/TreeView.cs
> +            var oldValue = SelectedItem;
`oldValue` doesn't seem to be used?

2020-10-08 11:00 UTC, danwalmsley commented on tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
> +            private int _counter;
removed.

2020-10-08 11:00 UTC, danwalmsley commented on src/Avalonia.Controls/TreeView.cs
> +            var oldValue = SelectedItem;
removed.

2020-10-08 13:04 UTC, grokys approved these changes

2020-10-08 16:38 UTC, merged