Add a CompositeTransition to Avalonia.Visuals
AvaloniaUI/Avalonia pull request #4790
Opened 2020-10-01 17:34 UTC by worldbeater

## What does the pull request do?

This PR adds a `<CompositeTransition />` animation class that implements `IPageTransition` and allows us to combine execute multiple page transitions at once. This concept is quite similar to `TransitionCollection` used in UWP. Using this useful class, one can declare a ReactiveUI `RoutedViewHost` control like this:

```xaml
<reactiveUi:RoutedViewHost Router="{Binding Router}">
   <reactiveUi:RoutedViewHost.PageTransition>
       <CompositeTransition>
           <PageSlide Duration="0.5" />
           <CrossFade Duration="0.5" />
       </CompositeTransition>
   </reactiveUi:RoutedViewHost.PageTransition>
</reactiveUi:RoutedViewHost>
```

And this results in the following good-looking transition that is a combination of `PageSlide` and `CrossFade`:

![ezgif-3-ad496c61dfa0](https://user-images.githubusercontent.com/6759207/94843053-d42d3b80-0424-11eb-88b8-142765bf42c2.gif)

## What is the current behavior?

Currently, there is no way to use multiple transitions with a `RoutedViewHost` control. Also, during a conversation with @danwalmsley, we discovered that the `PageSlide` transition has a flicker effect, and combining `PageSlide` and `CrossFade` can be a possible way to avoid that.

## What is the updated/expected behavior with this PR?

Currently, there is a `CompositeTransition` that can be declared in XAML. Planning to add some unit tests sooner than later.

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

2020-10-01 21:51 UTC, worldbeater commented
Added `SlideIn(Out)Easing` and `FadeIn(Out)Easing` properties to `CrossFade` and `PageSlide` transitions to make the setup even more flexible. These properties can be declared in XAML, so, for example, the following markup:
```xaml
<reactiveUi:RoutedViewHost Router="{Binding Router}">
    <reactiveUi:RoutedViewHost.PageTransition>
        <CompositePageTransition>
            <CrossFade Duration="0.4">
                <CrossFade.FadeInEasing>
                    <LinearEasing />
                </CrossFade.FadeInEasing>
                <CrossFade.FadeOutEasing>
                    <LinearEasing />
                </CrossFade.FadeOutEasing>
            </CrossFade>
            <PageSlide Duration="0.4" Orientation="Vertical">
                <PageSlide.SlideInEasing>
                    <CircularEaseInOut />
                </PageSlide.SlideInEasing>
                <PageSlide.SlideOutEasing>
                    <CircularEaseInOut />
                </PageSlide.SlideOutEasing>
            </PageSlide>
        </CompositePageTransition>
    </reactiveUi:RoutedViewHost.PageTransition>
</reactiveUi:RoutedViewHost>
```
Results in the following behavior:

<img src="https://user-images.githubusercontent.com/6759207/94866722-89bdb600-0448-11eb-93a1-b707a914d961.gif" width="400"/>

And this markup:

```xaml
<reactiveUi:RoutedViewHost Router="{Binding Router}">
    <reactiveUi:RoutedViewHost.PageTransition>
        <CompositePageTransition>
            <CrossFade Duration="0.4">
                <CrossFade.FadeInEasing>
                    <LinearEasing />
                </CrossFade.FadeInEasing>
                <CrossFade.FadeOutEasing>
                    <LinearEasing />
                </CrossFade.FadeOutEasing>
            </CrossFade>
            <PageSlide Duration="0.5" Orientation="Vertical">
                <PageSlide.SlideInEasing>
                    <BounceEaseInOut />
                </PageSlide.SlideInEasing>
                <PageSlide.SlideOutEasing>
                    <CircularEaseInOut />
                </PageSlide.SlideOutEasing>
            </PageSlide>
        </CompositePageTransition>
    </reactiveUi:RoutedViewHost.PageTransition>
</reactiveUi:RoutedViewHost>
```

Produces the following:

<img src="https://user-images.githubusercontent.com/6759207/94867122-43b52200-0449-11eb-8062-986f52152596.gif" width="400"/>

2020-10-05 00:45 UTC, jmacato requested changes
all looks good except for a nit :) great stuff! @worldbeater :)

2020-10-05 00:45 UTC, jmacato commented on src/Avalonia.Visuals/Animation/CompositePageTransition.cs
> +        public List<IPageTransition> Transitions { get; set; } = new List<IPageTransition>();
`Transitions` by itself is a "reserved" keyword for Avalonia, let's rename this to `PageTransitions`

2020-10-05 10:30 UTC, jmacato approved these changes
LGTM!

2020-10-05 20:59 UTC, merged