Turn off light dismiss for non-toplevel menus.
AvaloniaUI/Avalonia pull request #5499
Opened 2021-02-16 15:47 UTC by grokys

#5295 enabled the light dismiss overlay for popups, which in turn broke submenu interactions (#5475). The fix seems to be simple: turn off light dismiss for non-toplevel menus. These menus will be in popups so this means their behavior will be reverted to that of before #5295.

Fixes #5475

2021-02-16 16:41 UTC, maxkatz6 reviewed
I was thinking to use whole parent popup as a OverlayInputPassThroughElement parameter instead of single parent menu item element. 
But this approach makes even more sense for me. 
One thing I want to test later, if light dismiss still works for Menu elements (for ContextMenu it should work in any way). 

Upd: I see, there is another popup in templates for "Menu > MenuItem" selector. It works good.

2021-02-16 17:52 UTC, maxkatz6 commented
We need similar changes for Default theme as well

2021-02-23 15:34 UTC, grokys commented
@maxkatz6 good point - done.

2021-02-23 16:13 UTC, maxkatz6 requested changes

2021-02-23 16:13 UTC, maxkatz6 commented on src/Avalonia.Themes.Default/MenuItem.xaml
>                     OverlayInputPassThroughElement="{Binding $parent[MenuItem]}"
```suggestion
```

2021-02-23 20:08 UTC, maxkatz6 approved these changes

2021-03-03 00:49 UTC, merged