Attach CloseOnClickChanged event handler for NotificationCard.
AvaloniaUI/Avalonia pull request #5605
Opened 2021-03-03 16:04 UTC by kmosegaard

## What does the pull request do?
This fixed issue #5411.

## What is the current behavior?
This re-attached the event handler for CloseOnClick done a button inside a NotificationCard.

## What is the updated/expected behavior with this PR?
When clicking a button inside a NotificationCard and CloseOnClick is set to true then the NotificationCard should close when button is clicked.

## How was the solution implemented (if it's not obvious)?
This re-attaches an already implemented event handler that was disabled probably because of some refactoring.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

2021-03-03 16:04 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5605) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5605) before we can accept your contribution.<br/><br/>:x: kmosegaard [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5605)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=5605) it.</sub>

2021-03-06 14:32 UTC, MarchingCube commented
Thanks for your contribution, it indeed seems that many things have been overlooked in this class over time. But your solution will not work in all the cases sadly.

`SetCloseOnClick` is generally invoked by the compiler but one case also write `SetValue(CloseOnClickProperty, true)` directly and this change won't be picked up.

Canonical way of handling such properties is to register a class handler for it for given control type `Button` in this case. This way all changes will be picked up. Example: https://github.com/AvaloniaUI/Avalonia/blob/5332e3474194c7bc3674b8a97b8040d8a1ae5200/src/Avalonia.Controls/Grid.cs#L31

I've also noticed that property definition is a bit off and it should be `AttachedProperty<bool>` to avoid boxing and casting as well. Example: https://github.com/AvaloniaUI/Avalonia/blob/5332e3474194c7bc3674b8a97b8040d8a1ae5200/src/Avalonia.Controls/Grid.cs#L2721

Let me know if you can apply these changes yourself, otherwise I might be able to fix this class.

2021-03-07 12:19 UTC, kmosegaard commented
Hi MarchingCube.

Thanks for the pointers! I've tried to incorporate some of the feedback that you've given me. I'm a little in doubt whether connecting to the Button's Close event handler is still the way to go?

This change also prompts an ApiCompat build error. Is this okay?

Also, I've tested that the current change works in the ControlCatalog app. Are there any other ways to test this?

Regards, Kristian.

2021-03-07 22:36 UTC, MarchingCube requested changes
A few minor changes needed.
About testing - I think this control lacks any unit tests which will be useful to prevent such regressions from occurring again (cc @danwalmsley ). Although it does not need to be addressed in this PR.

About API changes - I think this change is fine since we are just making property type explicit.
To fix your build you will need to run command from https://github.com/AvaloniaUI/Avalonia/wiki/ApiCompat---Diffs in the directory of affected project. You can then commit updated api diff file.

2021-03-07 22:36 UTC, MarchingCube commented on src/Avalonia.Controls/Notifications/NotificationCard.cs
> +                CloseOnClickProperty.Changed.AddClassHandler<Button>(OnCloseOnClickPropertyChanged);
This should be in `static` constructor otherwise each `NotificationCard` instance will add extra handlers.

2021-03-07 22:36 UTC, MarchingCube commented on src/Avalonia.Controls/Notifications/NotificationCard.cs
> +            var button = d as Button;
A regular cast is enough, this one will raise warnings with nullable reference types enabled.

2021-03-08 07:55 UTC, kmosegaard commented
I've addressed the requested changes. Please say so if more is required.

2021-03-08 08:13 UTC, MarchingCube approved these changes
All good now. Thanks!

2021-03-08 08:16 UTC, kmosegaard commented
Cool beans. Thank you!

2021-03-08 09:35 UTC, merged