Api to allow loading WriteableBitmap from File / Stream
AvaloniaUI/Avalonia pull request #5800
Opened 2021-04-19 18:24 UTC by danwalmsley

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

## Fixed issues

2021-04-21 09:44 UTC, Szpoti approved these changes
Code looks good, its a usefull feature to have.
One thing I dont quite understand is why are there a bunch of functions with
``` throw new NotImplementedException(); ``` inside? Will these be changed or they have some other purpose?

2021-04-21 11:58 UTC, grokys commented on src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
> +        /// Create immutable bitmap from given stream.
An immutable writeable bitmap?

2021-04-30 16:36 UTC, danwalmsley commented
> Code looks good, its a usefull feature to have.
> One thing I dont quite understand is why are there a bunch of functions with
> `throw new NotImplementedException();` inside? Will these be changed or they have some other purpose?

Ah these are because they are test stubs, and these methods dont get tested from every test stub (or even at all)

hence notimplemented... but those methods are not part of the actual framework, just the testing part.

2021-05-11 09:45 UTC, MarchingCube requested changes
Mostly fine but there are a few smaller problems.

2021-05-11 09:45 UTC, MarchingCube commented on src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
> +        /// Loads a WriteableBitmap implementation from a file..
```suggestion
        /// Loads a WriteableBitmap implementation from a file.
```

2021-05-11 09:45 UTC, MarchingCube commented on src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
> +                Dpi = new Vector(96, 96);
```suggestion
                Dpi = SkiaPlatform.DefaultDpi;
```

2021-05-11 09:45 UTC, MarchingCube commented on src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
> +                Dpi = new Vector(96, 96);
```suggestion
                Dpi = SkiaPlatform.DefaultDpi;
```

2021-05-11 21:25 UTC, danwalmsley commented on src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
> +        /// Loads a WriteableBitmap implementation from a file..
doine.

2021-05-11 21:25 UTC, danwalmsley commented on src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
> +        /// Loads a WriteableBitmap implementation from a file..
done.

2021-05-12 08:02 UTC, MarchingCube approved these changes
LGTM. Noticed two minor doc issues that I've missed before.

2021-05-12 08:02 UTC, MarchingCube commented on src/Avalonia.Visuals/Media/Imaging/WriteableBitmap.cs
> +        /// <returns>An instance of the <see cref="Bitmap"/> class.</returns>
```suggestion
        /// <returns>An instance of the <see cref="WriteableBitmap"/> class.</returns>
```

2021-05-17 03:28 UTC, merged