Disable/Enable Close traffic-light (button) on Mac OSX
AvaloniaUI/Avalonia pull request #6306
Opened 2021-07-26 17:17 UTC by time4OSDev

(This is my first PR with you guys, so, if you would give me a little leeway.)

I am proposing in this PR the ability to Disable and Enable the Close traffic light on the Mac in Avalonia windows. Currently, you guys do have an EnableClose property on the Window control, but I could not find where on earth you implement it. I did find deep in your code you are doing what I found on Microsoft's sites: EnableMenuItem Win32 calls to implement the DisableCloseButton/EnableCloseButton for Windows. I decided to dig in and find out where and how to do it on Mac.

There are those in my company that brought up the valid point, when I had 'EnableCloseButton' and 'DisableCloseButton' as the methods, and they said why not just EnableClose.
1. This may imply, as they questioned, that it would mean also the Alt-F4/Cmd-W keystrokes and the upper-left (Windows) menu close and Dock right-click -> Quit (OSX) disabling as well.

I would like to propose, if you could, take this Mac implementation (in fact, or as suggestion), to have the feature on OSX, and, I think a micro and macro level of control for the traffic lights on OSX and on Windows be just button, button | menu | keystroke.

Humbly submitted.

PS. In Sandbox is a PoC showing the Disable/Enable on Mac.
If I found how you were making it the EnableClose property in Windows (from low-level win32 call), I would have liked to replicate for OSX. I.e., as property setter, rather than method calls.

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

2021-07-26 17:17 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6306) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6306) before we can accept your contribution.<br/><br/>:x: time4OSDev [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6306)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=6306) it.</sub>

2021-08-13 14:42 UTC, grokys requested changes
Gave this an initial look over, I have a few comments.

@kekekeks how do you feel about adding this feature. It's obviously not available on all platforms, but we've started adding features that aren't available everywhere if the APIs are documented as to their platform limitations.

2021-08-13 14:42 UTC, grokys commented on samples/ControlCatalog.Desktop/Program.cs
> +                .With(new AvaloniaNativePlatformOptions
This is debug code I assume? Should be removed.

2021-08-13 14:42 UTC, grokys commented on samples/Sandbox/Program.cs
> +                .With(new AvaloniaNativePlatformOptions
Again, debug code.

2021-08-13 14:42 UTC, grokys commented on src/Avalonia.Controls/Avalonia.Controls.csproj
> +  <!--
I think this needs to be uncommented.

2021-08-13 14:42 UTC, grokys commented on src/Avalonia.Controls/WindowBase.cs
> +        public void EnableCloseButton()
I'm not sure these methods should be added to `WindowBase`, shouldn't they be on `Window`? Popups don't have a close button.

2021-08-13 14:42 UTC, grokys commented on samples/Sandbox/MainWindow.axaml.cs
> +        private void DisableCloseButton_OnClick(object? sender, RoutedEventArgs e)
More debug code.

2021-08-13 14:42 UTC, grokys commented on samples/Sandbox/MainWindow.axaml
> +        <StackPanel Orientation="Horizontal">
More debug code.

2021-08-13 14:42 UTC, grokys commented on src/Avalonia.Native/WindowImpl.cs
> +        // public void EnableCloseButton()
Commented-out code should be removed.

2021-08-13 14:42 UTC, grokys commented on src/Avalonia.Native/WindowImplBase.cs
> +        public virtual void DisableCloseButton()
Should be moved to `WindowImpl` I think as mentioned elsewhere.

2021-08-13 14:42 UTC, grokys commented on src/Windows/Avalonia.Win32/PopupImpl.cs
> +        public void DisableCloseButton()
These can be moved from `PopupImpl` if the feature is moved from `WindowBase` to `Window`.

2021-08-13 14:42 UTC, grokys commented on src/Avalonia.Controls/WindowBase.cs
> +        public void DisableCloseButton()
Any reason you implemented these as methods and not as a property? Other similar features are generally implemented as a property.

2022-03-10 09:47 UTC, jmacato commented
Closing this due to inactivity and unresolved merge conflicts. Please ping me if you want to work on this again.

2022-03-10 09:47 UTC, closed without merging