[Menu] [Performance] Improve Menu item can execute logic. Make it work like in WPF
AvaloniaUI/Avalonia pull request #6438
Opened 2021-08-18 13:40 UTC by Mikolaytis

## What does the pull request do?
Improved CanExecute evaluation logic of MenuItem

## What is the current behavior?
CanExecute evaluation is called on any set of Command/CommandParameter even if menu is not open. this is affecting startup performance

## What is the updated/expected behavior with this PR?
CanExecute is called only on and when menu is opened. 

## Checklist
- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?

## Fixed issues
Fixes #6434

2021-08-23 20:48 UTC, grokys requested changes
Just tried this and it seems to make all menus in ControlCatalog.NetCore disabled. I think there's something wrong with the logic somehere?

2021-08-23 20:48 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
> +        public void MenuItem_Is_Disabled_Bound_Command_Is_Removed()
Why the change in name here? The removal of "when" makes it grammatically incorrect.

2021-08-23 20:48 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
> +        public void MenuItem_Not_Invokes_CanExecute_When_ContextMenu_Closed()
```suggestion
        public void MenuItem_Does_Not_Invoke_CanExecute_When_ContextMenu_Closed()
```

2021-08-23 20:48 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
> +        public void MenuItem_Not_Invokes_CanExecute_When_MenuFlyout_Closed()
```suggestion
        public void MenuItem_Does_Not_Invoke_CanExecute_When_MenuFlyout_Closed()
```

2021-08-23 20:48 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
> +        public void MenuItem_Not_Invokes_CanExecute_When_Parent_MenuItem_Closed()
```suggestion
        public void MenuItem_Does_Not_Invoke_CanExecute_When_Parent_MenuItem_Closed()
```

2021-08-25 00:50 UTC, Mikolaytis commented
> Just tried this and it seems to make all menus in ControlCatalog.NetCore disabled. I think there's something wrong with the logic somehere?

Looks like it is! I will check everything, add more tests, and will fix it.

2021-08-28 18:18 UTC, Mikolaytis commented
Now it's looks like fixed. 
Also I will try to find this PR build in avalonia-all nuget, add it to our app and call our QA to check if there is any issues.
If they will find something - I will write here and provide a fix. If no messages from me for a week - all fine.

2021-08-31 20:55 UTC, Mikolaytis commented
Our QA tested this on out app (we have lot's of menus). Did not found any issues.

2021-08-31 21:23 UTC, kekekeks commented
@grokys

2021-12-11 00:15 UTC, maxkatz6 approved these changes

2021-12-11 01:15 UTC, merged