Fix avalonia resource generation on resource deletion
AvaloniaUI/Avalonia pull request #6569
Opened 2021-09-10 08:31 UTC by Takoooooo

## What is the current behavior?
When you will add e.g Window and then delete it compilation would fail.

## What is the updated/expected behavior with this PR?
Everything works.

## Fixed issues
closes #4968

2021-09-10 08:33 UTC, Takoooooo commented
@MarchingCube Would it be possibe for you to verify? Does it work for you?

2021-09-10 10:16 UTC, MarchingCube commented
@Takoooooo Yep, I will check this locally.

2021-09-10 13:19 UTC, MarchingCube commented
@Takoooooo This PR is fixing this issue. I've followed my own repro steps and with this PR I can compile just fine after deleting views. In master this is still failing.

2021-09-20 08:46 UTC, kekekeks requested changes
Rename the target to `_GenerateAvaloniaResourcesDependencyCache` to match `_GenerateCompileDependencyCache` from msbuild

Also add `CustomAdditionalGenerateAvaloniaResourcesInputs` property group and use that instead of hardcoding the path to `GenerateAvaloniaResources` (that also matches msbuild)

For the reference: https://github.com/dotnet/msbuild/blob/f0eebf2872d76ab0cd43fdc4153ba636232b222f/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3529-L3548

2021-09-20 08:48 UTC, kekekeks commented on packages/Avalonia/AvaloniaBuildTasks.targets
> +      <Output TaskParameter="HashResult" PropertyName="UpdatedInputCacheContents" />
Use `AvaloniaResourcesDependencyHash`. It's a good idea to prefix properties like that to avoid name clashes with other nuget packages

2021-09-20 16:22 UTC, kekekeks approved these changes

2021-09-20 16:55 UTC, merged