Implement CornerRadius for Cairo
AvaloniaUI/Avalonia pull request #672
Opened 2016-08-07 02:13 UTC by nc4rrillo

2016-08-07 02:52 UTC, nc4rrillo commented
Fixes #349

2016-08-07 16:20 UTC, jkoritzinsky commented
Code looks good to me! I also notice that we don't have a render tests for corner radius on any of our rendering systems. Any chance you can add a render test for this?

I can help you with making the render test if you want.

2016-08-07 16:32 UTC, nc4rrillo commented
I've never made one, I'd love to learn though.

2016-08-07 16:52 UTC, jkoritzinsky commented
So you'll probably want to add your tests to the https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.RenderTests/Shapes/RectangleTests.cs file. Running the tests creates a *.out.png file (in the RenderToFile method) and compares it to the *.expected.png file with the same name (in the CompareImages method). The test file directories for the rectangle tests are ./tests/TestFiles/{RenderingSystem}/Shapes/Rectangle.

We don't have a good way to create the expected images, so we just run the test and generate the .out.png images. If the out images look right, then we rename them to be .expected.png. One way to do it is to run the test on one platform (like Direct2D1) and then copy the image into the other directories.

2016-10-15 11:18 UTC, danwalmsley commented
@jkoritzinsky will try and add a render test for this, would be nice to get this merged in.

2017-05-20 04:59 UTC, mageos requested changes
Overall it looks pretty good, but I think there are some minor refactors that would make the code a bit cleaner and more maintainable going forward.

2017-05-20 04:59 UTC, mageos commented on src/Gtk/Avalonia.Cairo/Media/DrawingContext.cs
> +				using (var p = SetPen (pen, rect.Size)) {
You can move the using statement to be outside the if\else block to reduce the duplication

2017-05-20 04:59 UTC, mageos commented on src/Gtk/Avalonia.Cairo/Media/DrawingContext.cs
> +					_context.NewSubPath ();
This block for drawing a rectangle could be extracted into a method so that it is can be used in both DrawRectangle and FillRectangle

2017-08-27 13:15 UTC, grokys commented
Closing this as it's very old and we're going to 🔥 cairo soon anyway. Thanks anyway @nc4rrillo !

2017-08-27 13:15 UTC, closed without merging