feat(ContentPresenter): Content of ContentPresenter should become DataContext of the subtree whenever ContentTemplate is not null
AvaloniaUI/Avalonia pull request #7008
Opened 2021-11-25 09:10 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

Fixes #6642

2021-12-06 13:08 UTC, grokys commented
Could we get some unit tests for this? `ContentPresenter` is pretty heavily tested at the moment, and doesn't make sense to not cover this is tests too.

2021-12-06 19:13 UTC, jp2masa commented on src/Avalonia.Controls/Presenters/ContentPresenter.cs
> +        private void UpdateChid(object content)
Nit: typo

2021-12-06 21:18 UTC, workgroupengineering commented on src/Avalonia.Controls/Presenters/ContentPresenter.cs
> +        private void UpdateChid(object content)
tnx

2021-12-13 10:49 UTC, workgroupengineering commented
> Could we get some unit tests for this? `ContentPresenter` is pretty heavily tested at the moment, and doesn't make sense to not cover this is tests too.

I think there is no need for it, there are so many tests that verify it.

2022-02-01 10:16 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0018395-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-03-10 10:17 UTC, jmacato commented
Closing due to inactivity. Please ping me if you're gonna work on this again.

2022-03-10 14:50 UTC, workgroupengineering commented
@jmacato This PR is complete. No further tests are needed because the behavior is extensively tested.

2022-03-10 15:24 UTC, jmacato commented
@workgroupengineering okay i'll reopen and ask for reviews

2022-03-10 16:22 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0019181-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-03-10 16:50 UTC, jmacato commented
@workgroupengineering please add additional test on this PR so that we dont break this in the future

2022-03-10 17:09 UTC, maxkatz6 approved these changes
LGTM

2022-03-10 17:13 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0019193-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-03-10 17:44 UTC, jmacato requested changes
just a nitpick :)

2022-03-10 17:44 UTC, jmacato commented on tests/Avalonia.Controls.UnitTests/Presenters/ContentPresenterTests_InTemplate.cs
> +        public void Content_Will_By_Datacontext_When_ControlTemplate_Is_Null()
`Content_Will_`?? Might be missing some word here?

2022-03-11 09:43 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0019230-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-03-11 14:10 UTC, jmacato approved these changes
LGTM!

2022-03-22 20:16 UTC, merged

2022-03-22 20:20 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0019436-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]