[Win] Open context menu on pen/touch hold
AvaloniaUI/Avalonia pull request #7417
Opened 2022-01-23 21:04 UTC by Mikolaytis

## What does the pull request do?
Now touch hold and pen hold opens context menu on windows.

## What is the current behavior?
Touch/pen hold does nothing

## Fixed issues
#6538

@maxkatz6 asked for client code solution via gestures. I think this is a bad way of implementation by a number of reasons:
1. this is a system gesture on windows. It has animation, configuration and so on.
2. my solution is way faster to implement. 1 line of code.
3. if we want our custom gesture - we should disable system gesture animations, invoke and make our own animation and invent ways to configure everything.

I do not force my solution. If you don't want it - it's ok. close this PR. I just share my solution to this issue.

After this PR there is a bug: context menu appears in a wrong position. This is because of a bug in `PopupPositionerExtensions.ConfigurePosition`. It uses only mouse device as a source of context menu position.
![Screenshot 2022-01-23 at 23 54 25](https://user-images.githubusercontent.com/4997065/150697903-67c10183-0fe3-44c1-a9d1-759275e52050.png)

I will create a PR that should fix this after a merge on WM_Pointer and PenDevice.

2022-01-26 12:37 UTC, grokys requested changes
Yep, I think it makes sense to raise a `ContextRequested` event in response to a `WM_CONTEXTMENU` message, though the exact mechanism might need to change.

2022-01-26 12:37 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
> +                        KeyboardDevice.Instance.FocusedElement?.RaiseEvent(new ContextRequestedEventArgs(pos));
Not sure that the `WindowImpl` should be reaching into the `KeyboardDevice` to get the currently focused element here.  The pattern used elsewhere is that events from the platform impl are delegated to the owner `Window` using `RawInputEventArgs`.

2022-01-26 17:20 UTC, kekekeks commented
Note that it can and _will_ conflict with whatever gesture recognizers we'd have. 

We could potentially add `HoldToRightClickGestureRecognizer` in managed code and offload the recognition to the supporting OS if original PointerPressed event was marked by said recognizer.

2022-01-27 08:54 UTC, grokys commented
> Note that it can and will conflict with whatever gesture recognizers we'd have.

Might it make sense to move all of our `ContextRequested` support to the OS? AFAIK the expected gestures vary by platform so might be the best place for them.

2022-01-27 09:12 UTC, kekekeks commented
>Might it make sense to move all of our ContextRequested support to the OS

1) not every OS has built-in gestures for press-n-hold
2) not every control needs context menu on press-n-hold, most of them don't even have a context menu

2022-06-18 11:14 UTC, Mikolaytis commented
Closing this PR because it done in a bad way. 
* no using of RawEventArgs
* no support for other platform via gesture recognizer.

2022-06-18 11:14 UTC, closed without merging