WIP: Implemented Skia DPI scaling.
AvaloniaUI/Avalonia pull request #771
Opened 2016-10-16 17:53 UTC by danwalmsley

Has a workaround for bug in DrawingContext.

2016-10-16 21:30 UTC, grokys requested changes

2016-10-16 21:30 UTC, grokys commented on src/Skia/Avalonia.Skia/DrawingContextImpl.cs
> +            _currentTransform =  Matrix.Identity * _dpiScaleMatrix;
You can think of `Matrix.Identity` as a 1 in a multiplication, so you don't need it here, as essentially you're saying `currentTranform = 1 * scale`. In other words ` Matrix.Identity * _dpiScaleMatrix == _dpiScaleMatrix`.

2016-10-16 21:30 UTC, grokys commented on src/Skia/Avalonia.Skia/DrawingContextImpl.cs
> +            _currentTransform =  Matrix.Identity * _dpiScaleMatrix;
However, you're not informing the `Canvas` of the matrix here...

2016-10-16 21:30 UTC, grokys commented on src/Skia/Avalonia.Skia/DrawingContextImpl.cs
> +                _currentTransform *= _dpiScaleMatrix;
...which is why I suspect you need this here. This is actually not doing the right thing: it's applying the scaling *after* the current transform, whereas it needs to be applied before.

2016-10-17 09:16 UTC, kekekeks commented on src/Skia/Avalonia.Skia.Desktop/RenderTarget.cs
> +#if WIN32
It's definitely not the job of rendering system to detect window DPI.

2016-10-17 09:19 UTC, kekekeks commented
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.SceneGraph/Media/DrawingContext.cs
This class is specifically designed to allow arbitrary transformations to be applied without touching underlying implementation. Just use `PushPostTransform` or `PushPreTransform` before returning the context instead of applying hacks like you do in this PR

2016-10-18 09:11 UTC, danwalmsley commented
@kekekeks 

" Just use PushPostTransform or PushPreTransform before returning the context instead of applying hacks like you do in this PR"

this didn't work.

 because:
https://github.com/AvaloniaUI/Avalonia/blob/85f07274d434b11d9aa722a491c2286fcf0791d7/src/Avalonia.SceneGraph/Rendering/RendererMixin.cs#L128
causes the scaled matrix to end up in RenderTransforms and it affects hittesting and adorner layers...
set here.... (and probably other places)
https://github.com/AvaloniaUI/Avalonia/blob/85f07274d434b11d9aa722a491c2286fcf0791d7/src/Avalonia.Controls/Primitives/AdornerLayer.cs#L62
any suggestions how I can resolve this?
I guess we really want to completely separate out DPI scaling

2016-10-18 16:08 UTC, kekekeks commented
@danwalmsley It *can't* affect render transforms in controls from there.

2016-10-19 08:51 UTC, merged