WIP: Fixes for Carousel
AvaloniaUI/Avalonia pull request #799
Opened 2016-11-08 16:50 UTC by danwalmsley

2016-11-12 12:58 UTC, grokys commented on src/Avalonia.Controls/Generators/ItemContainerGenerator.cs
> +
This could be written more succinctly as:

```
public virtual Type ContainerType => null;
```

2016-11-12 12:58 UTC, grokys commented on src/Avalonia.Controls/Generators/ItemContainerGenerator`1.cs
> +
Again here.

2016-11-12 12:59 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +            {
Whitespace

2016-11-12 13:00 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                        toAdd.Add((container.ContainerControl as ContentPresenter).Child as ILogical);
Cast this only once. Also if you're doing an `as` you need to check for null.

2016-11-12 13:01 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                        toRemove.Add((container.ContainerControl as ContentPresenter).Child);
Again, either use a standard cast here or if we want to handle cases where the item isn't a `ContentPresenter` put in a null check.

2016-11-12 13:37 UTC, danwalmsley commented on src/Avalonia.Controls/ItemsControl.cs
> +
done

2016-11-12 22:24 UTC, danwalmsley commented
@grokys last commit on this fixed a major bug for me. Basically if I didn't do the SetTemplatedParent null
before calling update child, then the Child would end up with the ItemsControls templatedParent as its Parent, this prevented the item getting removed from logical tree.

I spent ages really debugging this stuff in detail.. I would like to add a unit test to check this too.

I'm wondering if because of this we should remove this line...
https://github.com/VitalElement/AvalonStudio/commit/7b75d5a5a5a7332c3aa2dd3cdf669b7191fc384d

with the blog post you did on logical tree weirdness, then something could be a logical child and you want to remove it, even though its logical parent the control that wants to remove it... make sense?

2016-11-14 22:16 UTC, grokys requested changes

2016-11-14 22:16 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                                LogicalChildren.Add(containerControl.Child as ILogical);
You've already checked if `containerControl.Child` is an `ILogical` above, so this is unnecessarily casting twice.

2016-11-14 22:16 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                            toRemove.Add(containerControl.Child as ILogical);
Again, casting twice here.

2016-11-14 22:16 UTC, grokys commented on tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
> +                Assert.Equal(container.Child.Parent, container);
The order for `Assert.Equals` arguments is `expected, actual` so these two args should be swapped.

2016-11-14 22:18 UTC, grokys commented
LGTM, just added a few requests for small changes. Also your previous comment said:

> I'm wondering if because of this we should remove this line...
> VitalElement/AvalonStudio@7b75d5a

Is that the link you meant to paste?

2016-11-14 22:25 UTC, danwalmsley commented
I think this was the link I wanted to paste...

https://github.com/AvaloniaUI/Avalonia/blob/dec5682dce412f93b3f3bd85c4a697c726e4af78/src/Avalonia.Controls/Control.cs#L781

My thoughts were that it should always clear parent here, because it would prevent from being removed from logical tree, it the i.LogicalParent != this, which could happen?

But now thinking about it, seems like that would not be good!

2016-11-14 22:36 UTC, grokys commented
Yeah, I think the current behavior is correct. So PR LGTM (Lets Get This Merged) =D

2016-11-14 22:39 UTC, grokys requested changes

2016-11-14 22:39 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                            if (containerControl.Child is ILogical)
Only just noticed now that `containerControl.Child` is `IControl` which inherits from `ILogical` so this check is unnecessary.

2016-11-14 22:39 UTC, grokys commented on src/Avalonia.Controls/ItemsControl.cs
> +                        if (containerControl != null && containerControl.Child is ILogical)
Also this `is` check is unnecessary.

2016-11-14 22:39 UTC, danwalmsley commented on src/Avalonia.Controls/ItemsControl.cs
> +                                LogicalChildren.Add(containerControl.Child);
@grokys  Is it more efficient to add them to a list first, then do addrange.

I had at some point during the development needed to add them as I went along for some reason.
might be able to change back if there is a performance hit?

2016-11-14 22:44 UTC, danwalmsley commented on src/Avalonia.Controls/ItemsControl.cs
> +                                LogicalChildren.Add(containerControl.Child);
@grokys this one...

2016-11-14 22:46 UTC, grokys approved these changes

2016-11-15 08:51 UTC, merged

2016-11-15 10:06 UTC, grokys commented
Thanks Dan! Nice work :)