WIP Fixes/dont cover taskbar with system decorations hidden
AvaloniaUI/Avalonia pull request #805
Opened 2016-11-13 22:22 UTC by danwalmsley

2016-11-13 23:04 UTC, danwalmsley commented
Normal Size:
https://files.gitter.im/VitalElement/AvalonStudio/DnnH/image.png

Maximized:
https://files.gitter.im/VitalElement/AvalonStudio/zMCA/image.png

2016-11-13 23:28 UTC, danwalmsley commented
This only actually affects Windows backend, as on mac and Linux windows by default in this condition use the full desktop area rather than the full screen.

2016-11-13 23:38 UTC, danwalmsley commented
I'm also unsure how this can be unit tested? It doesn't really affect state of Window, only tell backend how to behave, unless we have any win32 specific unit tests?

2016-11-16 20:33 UTC, grokys requested changes

2016-11-16 20:33 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +                windowRect.left + oldThickness.Left,
Indenting seems to be broken here.

2016-11-16 20:33 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +                    {
Maybe the block below might be best refactored out into a separate method?

2016-11-16 21:36 UTC, grokys requested changes

2016-11-16 21:36 UTC, grokys commented on src/Avalonia.Controls/Window.cs
> +        /// Sets if the Window should Covert the taskbar when Maximized. Only applies to Windows
Covert? As in covert operations? ;) Also nit: we don't capitalize "Window" elsewhere, unless we're doing a `<see cref="Window">`

2016-11-16 21:36 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +                windowRect.left - thickness.Left,
Indentation still appears to be wrong here.

2016-11-16 21:36 UTC, grokys commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +                windowRect.top + oldThickness.Top,
And here.

2016-11-16 21:36 UTC, grokys commented on src/Avalonia.Controls/Window.cs
> +        /// When system window decorations are disables sets if the Window when maximized ignores the taskbar.
Could we use "covers the taskbar" here as well?

2016-11-16 22:12 UTC, grokys approved these changes

2016-11-16 22:12 UTC, grokys commented
Yep, LGTM!

2016-11-17 00:26 UTC, merged