[WIP] Wayland backend
AvaloniaUI/Avalonia pull request #8352
Opened 2022-06-16 09:50 UTC by affederaffe

## What does the pull request do?
Add a Wayland backend for Linux.
There hasn't been any activity on the [previous PR](https://github.com/AvaloniaUI/Avalonia/pull/8003), which is why I'm opening one on my own.
At the moment, you have to manually generate the Wayland bindings because I haven't figured out how to do so on build:
`cd ./src/Linux/NWayland/src/NWayland.CodeGen && dotnet run`
This PR is still WIP, help is greatly appreciated.

What currently works:
- [ ] Windowing:
    - [x] Window creation
    - [ ] Popups
    - [ ] Client Side decorations
- [ ] Keyboard:
    - [x] Basic input; some bugs left (e.g. backspace handling)
    - [x] Key repetition; partly
- [ ] Mouse:
    - [x] Basic handling
    - [x] Scrolling
    - [x] Theme cursors; partly
    - [x] Custom cursors
    - [ ] Animated cursors
- [ ] Touch:
    - [ ] Basic handling
- [ ] Data sharing:
    - [ ] Clipboard:
        - [x] Reading
        - [ ] Writing; currently very buggy
    - [ ] DND
- [ ] Rendering:
    - [x] EGL
    - [ ] FrameBuffer
    - [ ] Vulkan?

## What is the current behavior?
Currently, XWayland is used in order to run Avalonia apps on Wayland systems.

## What is the updated/expected behavior with this PR?
Use Wayland instead of X11 on compatible systems.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
Some projects where moved to the Linux solution.

## Obsoletions / Deprecations
None

## Fixed issues
Fixes #1243

2022-06-16 16:41 UTC, kekekeks commented
If Wayland bindings are stable, I'll publish a packaged version on nuget

2022-07-25 12:36 UTC, kekekeks commented
@affederaffe I believe we already have rudimentary CSD that are used for Win32 backend. Resize-grips are missing but other than that they are more or less usable even with X11.

2022-07-25 12:37 UTC, kekekeks commented
Ah, you were already trying to enable them, nvm

2022-07-25 13:22 UTC, affederaffe commented
Neither resize nor move seem to be currently implemented and the X11 backend doesn't support CSD either, so I thought I'd disable them for now.

2022-07-25 20:55 UTC, affederaffe commented
@kekekeks Any plans on releasing NWayland on NuGet?

2022-08-21 04:17 UTC, jmacato requested changes
@affederaffe @kekekeks this doesnt seem to work on GNOME coz i got this message

```
Unhandled exception. System.NotSupportedException: Unable to find zxdg_decoration_manager_v1 in the registry
   at Avalonia.Wayland.WlRegistryHandler.Bind[T](IBindFactory`1 factory, String interface, Int32 version) in /var/home/strix/RiderProjects/AvaloniaM/src/Linux/Avalonia.Wayland/WlRegistryHandler.cs:line 59
   at Avalonia.Wayland.WlRegistryHandler.BindRequiredInterface[T](IBindFactory`1 factory, String interface, Int32 version) in /var/home/strix/RiderProjects/AvaloniaM/src/Linux/Avalonia.Wayland/WlRegistryHandler.cs:line 49
   at Avalonia.Wayland.AvaloniaWaylandPlatform..ctor(WaylandPlatformOptions options) in /var/home/strix/RiderProjects/AvaloniaM/src/Linux/Avalonia.Wayland/AvaloniaWaylandPlatform.cs:line 37
   at Avalonia.AvaloniaWaylandPlatformExtensions.<>c__0`1.<UseWayland>b__0_0() in /var/home/strix/RiderProjects/AvaloniaM/src/Linux/Avalonia.Wayland/AvaloniaWaylandPlatform.cs:line 156
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /var/home/strix/RiderProjects/AvaloniaM/src/Avalonia.Controls/AppBuilderBase.cs:line 280
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /var/home/strix/RiderProjects/AvaloniaM/src/Avalonia.Controls/AppBuilderBase.cs:line 148
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /var/home/strix/RiderProjects/AvaloniaM/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at ControlCatalog.NetCore.Program.Main(String[] args) in /var/home/strix/RiderProjects/AvaloniaM/samples/ControlCatalog.NetCore/Program.cs:line 103
```

`cd ./src/Linux/NWayland/src/NWayland.CodeGen && dotnet run` should be updated to ` cd ./src/Linux/NWayland/src/NWayland.Scanner && dotnet run`

2022-08-21 08:58 UTC, kekekeks commented
@jmacato you need to use a desktop environment that supports server decorations. Basically not GNOME.

2022-08-21 17:54 UTC, jmacato commented
@affederaffe im still getting the same error in gnome on the latest commit:
![image](https://user-images.githubusercontent.com/16554748/185804413-8ffd4b65-7bc5-436c-a439-33d203920d3d.png)

2022-08-21 18:05 UTC, kekekeks commented
Yes, your desktop environment needs to support Server Side Decorations. Please, check with desktop environment that supports `zxdg_decoration_manager_v1`

2022-08-21 19:43 UTC, affederaffe commented
Decorations seem to work on Gnome now, though I noticed that popups and drag&drop are completely broken on it, even though they work perfectly fine on KDE.

2022-08-22 04:07 UTC, jmacato commented
![image](https://user-images.githubusercontent.com/16554748/185837558-3690d4ab-5531-466a-abd4-084a271bad22.png)
This is wild :D but it seems like that we need a way to add CSD on windows that didnt specify it. I know GNOME is a bit thickheaded but it's a major DE that we cannot ignore.

2022-08-24 08:24 UTC, jmacato commented
@affederaffe this is so amazing :D i can do DnD on linux now :D thanks so much for this effort!

btw, some more bug reports if you dont mind:

![image](https://user-images.githubusercontent.com/16554748/186368648-33ee5927-188d-4c9a-94ec-ffea50a058fb.png)

Some windows still doesnt have CSD for some reason, like the DevTools window for example

2022-08-27 05:13 UTC, jmacato commented
@affederaffe @kekekeks im curious, is it possible to make a RenderTimer that is synchronized to the Compositor's refresh rate?

2022-08-27 06:34 UTC, kekekeks commented
You can ask the compositor to send you a callback when it thinks that's a good idea to start rendering a new frame. However for that to work each window would have its own render timer. While being possible to refactor our rendering to use multiple render timers, I'm afraid the UI thread animations like their global variables a bit too much, so we can't do that.

2022-08-28 03:03 UTC, jmacato commented
@kekekeks by global variables you mean the inherited Clocks?

2022-08-28 05:51 UTC, kekekeks commented
Yes, UI thread animations expect to have some global clock to function.

2022-08-28 07:09 UTC, jmacato commented
@kekekeks that can be refactored yes, inherently we only need a way to hand over some kind of timer to the clocks

2022-08-28 09:43 UTC, kekekeks commented
>each window/surface can have one timer each and it should work fine

Animations can tick on brushes in resource dictionaries that are shared by multiple windows.

2022-09-08 19:37 UTC, Conan-Kudo commented
You might want to look into [libdecor](https://gitlab.gnome.org/jadahl/libdecor) for handling SSD-less compositors (basically just Mutter from GNOME).

2022-09-09 05:17 UTC, kekekeks commented
Last time I've checked libdecoration required glib and wasn't really thread safe, which is important because Avalonia does event handling/layout and rendering on different threads.

2022-09-09 08:55 UTC, jmacato commented
@kekekeks i like having our own CSD implementation better tbh. That way users can modify it so without much fuss.

2022-10-10 11:43 UTC, jmacato requested changes
![image](https://user-images.githubusercontent.com/16554748/194858609-5980c950-67aa-4173-8115-39b13f157501.png)

I cant seem to build this in a fresh clone

2022-10-10 11:54 UTC, affederaffe commented
@jmacato You need to add
`<ItemGroup Label="InternalsVisibleTo">
        <InternalsVisibleTo Include="NWayland.Protocols.Plasma, PublicKey=$(AvaloniaPublicKey)" />
        <InternalsVisibleTo Include="NWayland.Protocols.Wlr, PublicKey=$(AvaloniaPublicKey)" />
    </ItemGroup>`
for the time being, that'll be fixed once the bindings are published on NuGet.

2022-10-10 14:02 UTC, jmacato commented
@affederaffe im getting this error now as well, fixed the public sigs though with your comment
![image](https://user-images.githubusercontent.com/16554748/194884137-f56687bb-296f-4620-907f-4afb707ba937.png)

2022-10-10 14:36 UTC, affederaffe commented
@jmacato Update the NWayland submodule and regenerate the bindings

2022-10-11 04:44 UTC, jmacato requested changes
@affederaffe please fix the latest merge conflict with master, i tested this PR and it's working great so far :D 

Just noticed some issues:

- Copy/Paste/Clipboard doesnt seem to parse and decode Unicode characters.
- Frame rate is still locked to 60fps for high refresh rate monitors but im not sure if that's fixable in this current PR.
- OpenGL doesnt seem to work on dedicated GPU only setup.

I dont think we can merge until we can get a new NWayland package from @kekekeks. Or at least make NWayland use sourcegens instead, not sure.

Anyways this is a very much needed backend since X11 going to be endangered species in the next few years.

2022-10-12 23:21 UTC, affederaffe commented
I opened a PR with my fixes for NWayland [here](https://github.com/kekekeks/NWayland/pull/1).

- Should Copy/Paste decode entered unicode codes? As far as I know hard-coded charachters are decoded correctly and only those entered by the user are escaped, just like with X11.
- The framerate can easily be unlocked once there's a solution for brushes ticking in ResourceDictionaries as discussed above.
- This seems to be an issue with shared contexts with the EGL backend and doesn't work on X11 either. I can try to fix this, though I have no knowledge on this so I'd appreciate a little help.

2022-10-21 01:34 UTC, jmacato commented
@affederaffe im waiting for @kekekeks to review your PR on NWayland's repo. After he publishes the nuget we can get this PR merged :)

2022-10-23 14:36 UTC, jmacato commented on src/Linux/Avalonia.FreeDesktop/LibC.cs
> +        public static extern unsafe int poll(pollfd* fds, int nfds, int timeout);
I wonder if we can use `nuint` on this?

2022-11-05 12:04 UTC, jmacato commented
@affederaffe Seems like the FPS overlay is not displaying correctly on Gnome?
![image](https://user-images.githubusercontent.com/16554748/200118968-6202468f-25f8-4270-93d2-3afe137c41a3.png)

2022-11-12 05:23 UTC, squidink7 commented
I just tried this on Arch Linux KDE, and found issues related to maximising. The window would only maximise to a small portion of the actual screen size, and would become even smaller when any other window was focused
![image](https://user-images.githubusercontent.com/56238661/201458200-c01350e5-22d4-4881-af33-dbc6b06ccdeb.png)
I also needed to remove the InternalsVisibleTo lines in the NWayland project file or no apps would build.
Very nice work though, other than that everything was working well as far as I saw!

2023-02-07 03:50 UTC, robloo commented
Hope there is discussion with the core team on this and a plan for merging. Really should have been merged in before the RC in my opinion (so by preview 5). It needs a chance for good testing before release.

2023-03-08 12:31 UTC, timunie commented
Hey @affederaffe ,

I want to reach out for you as 11.0 is going to be closer and this PR is a really huge PR. We really appreciate your efforts and it is on our todo-list to get it merged. But most likely it will not be included in 11.0, as 11.0 has already a lot of new stuff inside. We plan to add this feature in a 11.x release after the major 11.0 bugs are ironed out. 

I hope for your understanding 💐 


Happy coding

Tim

2023-03-08 14:21 UTC, affederaffe commented
I completely understand, also there are still some bugs left I haven't had the time to fix yet and probably won't in the near future, so it's definitely for the better. Still, I plan to work on this PR eventually, it is _not_ abandoned.

2023-03-08 14:46 UTC, timunie commented
Okay, so we are on the same route. That's great. I think it is a good idea to merge master as you already do it in order to not get too much out of sync. Anything else can be done later 👍 

Have a nice day.

2023-03-09 06:08 UTC, kekekeks commented
To be clear: we are planning to extract any changes to Avalonia core libs from this PR and merge them before 11.0. That way the rest of Wayland support could be merged later in 11.x.

2023-03-14 00:13 UTC, jgcodes2020 commented
If it's helpful, here's an alternative Wayland scanner: https://github.com/X9VoiD/WaylandSharp

2023-04-04 20:03 UTC, nicola36631 commented
@affederaffe is there some way the community can help with this PR? What is still missing/not working at the moment?

2023-04-05 05:05 UTC, kekekeks commented
Note that the way CSD are implemented kinda interferes with Window's Width/Height controlling the client area size. So it probably can't be merged as is and would require some major changes in either TopLevel or composition code.

2023-04-06 16:17 UTC, jgcodes2020 commented
> Note that the way CSD are implemented kinda interferes with Window's Width/Height controlling the client area size. So it probably can't be merged as is, proper CSD would require some major changes in either TopLevel or composition code.

Proper CSD might be worth splitting into a separate PR, since there are already a lot of changes here. All that matters for a Wayland backend is that it runs on GNOME (which has no current or planned `xdg-decoration` support).

2023-04-06 17:01 UTC, kekekeks commented
Gnome is pretty much the only "very special child" that needs us to implement CSD. Without CSD it won't show any window frame.

We could merge Wayland without CSD and ignore gnome for now since it would enable some embedded device scenarios that are running fullscreen anyways.

2023-04-06 17:40 UTC, nicola36631 commented
> > Note that the way CSD are implemented kinda interferes with Window's Width/Height controlling the client area size. So it probably can't be merged as is, proper CSD would require some major changes in either TopLevel or composition code.
> 
> Proper CSD might be worth splitting into a separate PR, since there are already a lot of changes here. All that matters for a Wayland backend is that it runs on GNOME (which has no current or planned `xdg-decoration` support).


I think that supporting GNOME and KDE Plasma (best looking) and XFCE (most lightweight) is quite important as they are "the top dogs" of desktop environments on Linux.


Perhaps improving Client Side Decorations is an issue that can be moved to the 11.x milestone?

2023-04-24 10:35 UTC, closed without merging

2023-04-24 11:21 UTC, Doomsdayrs commented
Closed??

2023-04-24 11:24 UTC, zoujiaqing commented
Wow...

2023-04-24 11:31 UTC, robloo commented
Hopefully this is just closed because the strategy was changed a bit for 11.0

1. Pull out the core changes it needs and get those in for 11.0
2. Finish and merge this in the 11.x series in a separate PR

If this was closed because it is no longer developed that is most unfortunate. It should have been merged as-is and provided a good base for everyone to test and patch from. 95% was more than OK in my opinion for a previously unsupported backend.

2023-04-24 11:56 UTC, affederaffe commented
I'm just starting to rebase my patches onto master and I decided it's easier to do so on a new branch. That comes with the advantage of a clean master branch and a feature branch, like it should've been from the start. The wayland backend still needs some work and I don't have that much time in the coming weeks, after that I do though.