fix: DBus Null annotations
AvaloniaUI/Avalonia pull request #8451
Opened 2022-07-06 07:51 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

2022-07-06 08:17 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0021630-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-07-09 21:48 UTC, kekekeks commented on src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxICWrapper.cs
> +        public Task FocusInAsync() => _old?.FocusInAsync() ?? _modern?.FocusInAsync() ?? Task.CompletedTask;
One of `_old` or `_modern` is guaranteed to be non-null.

2022-07-09 21:51 UTC, kekekeks approved these changes
In general lgtm

2022-07-09 22:40 UTC, jmacato requested changes, later dismissed
there's some that seems like it's autogenerated changes in the sln and proj files, please remove those.

2022-07-09 22:40 UTC, jmacato commented on Avalonia.sln
> +		src\Shared\IsExternalInit.cs = src\Shared\IsExternalInit.cs
What is this file for?

2022-07-09 22:40 UTC, jmacato commented on src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
> +    <Compile Include="..\Shared\IsExternalInit.cs" Link="IsExternalInit.cs" />
This as well, i cant find it in the PR?

2022-07-09 23:00 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0021788-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-07-10 00:21 UTC, maxkatz6 commented on Avalonia.sln
> +		src\Shared\IsExternalInit.cs = src\Shared\IsExternalInit.cs
Adds a file to the solution tree

2022-07-10 00:21 UTC, maxkatz6 commented on src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
> +    <Compile Include="..\Shared\IsExternalInit.cs" Link="IsExternalInit.cs" />
IsExternalInit is required for records

2022-07-10 10:35 UTC, merged

2022-07-10 10:40 UTC, avaloniaui-team commented
You can test this PR using the following package version. `0.10.999-cibuild0021796-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]