Buttons are disabled when there is a null in the binding chain for Command
AvaloniaUI/Avalonia pull request #894
Opened 2017-02-12 06:27 UTC by jkoritzinsky

Fixes #846.

2017-02-12 10:56 UTC, kekekeks commented on src/Avalonia.Controls/Button.cs
> +        public static readonly DirectProperty<Button, ICommand> CommandProperty =
If I remember correctly, direct properties lack some features. So It's probably better to subscribe to property change notification here.

2017-02-12 21:06 UTC, jkoritzinsky commented on src/Avalonia.Controls/Button.cs
> +        public static readonly DirectProperty<Button, ICommand> CommandProperty =
The subscription to the property changed notification happens in the static constructor. It still works with DirectProperties

2017-02-14 19:42 UTC, grokys requested changes
I tried adding [a few unit tests](https://gist.github.com/grokys/1ddb942f8a0a49090eef59ec0349e452) to test this and found some problems.

The first problem is caused by [this code](https://github.com/AvaloniaUI/Avalonia/blob/e03187073879bd19d54959ca0411b2f4d322a139/src/Markup/Avalonia.Markup/Data/ExpressionObserver.cs#L242-L252) which results in the binding error not being notified on null. I think we probably need to remove this code - for the moment that will spew a load of unwanted warnings but I think we need to address that a different way in another PR.

The second problem is that if the `Command` is updated to point to a disabled `ICommand` then the button will be enabled even when it should be disabled.

2017-05-01 19:00 UTC, kekekeks commented on Avalonia.sln
> +VisualStudioVersion = 15.0.26403.3
Duplicate

2017-05-07 11:47 UTC, grokys commented
@jkoritzinsky thanks for updating - I'm not ignoring this but I want to do a proper review and merge it after we've released alpha 5 if that's ok?

2017-05-07 11:47 UTC, jkoritzinsky commented
Sure!

2017-07-10 07:50 UTC, grokys approved these changes

2017-08-21 19:44 UTC, merged