WIP: Fix setting WindowState before showing Window.
AvaloniaUI/Avalonia pull request #9221
Opened 2022-10-18 07:32 UTC by grokys

## What does the pull request do?

As described in #8869, on Win32 if one sets the `Window` `(`Min`/`Max`)/`Width`/`Height` together with `WindowState` before showing the window, the `Maximized`/`FullScreen` `WindowState` is ignored.

This PR changes the win32 backend to ignore resize requests when the window is maximized or fullscreen.

## Fixed issues

Fixes #8869

2022-10-18 07:56 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0024896-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-10-21 21:32 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025172-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-10-21 23:04 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025183-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-17 14:47 UTC, danwalmsley requested changes

2022-11-17 14:47 UTC, danwalmsley commented on src/Windows/Avalonia.Win32/WindowImpl.cs
> +            if (WindowState is WindowState.Maximized or WindowState.FullScreen)
Or minimized? 

!= Normal?

2022-11-17 15:01 UTC, danwalmsley approved these changes

2022-11-18 00:54 UTC, merged

2022-11-23 13:44 UTC, grokys commented
Backported to 0.10.x: ffe74ceaa49b7be878c006c030422bf2d5b0fa73