Add Status Bar Api
AvaloniaUI/Avalonia pull request #9281
Opened 2022-10-26 08:47 UTC by emmauss

## What does the pull request do?
Adds Status Bar api through `ITopLevelWithPlatformStatusBar`, with color and visibility properties. The Api can be accessed on any Control instance, but is only applied when using the TopLevel's Content, ie the MainView. This Api is targeted toward mobile platforms.

New Properties in `Control`;
```csharp
Color StatusBarColor { get; set; }

bool? IsStatusBarVisible { get; set; }
```

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

2022-10-26 09:10 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025421-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-10-26 09:29 UTC, Gillibald commented
If this only applies to the TopLevel why are we defining the property on Control level?

2022-10-31 09:20 UTC, danwalmsley requested changes
we can refactor it a little so that most of the code doesnt go inside toplevel.cs (but still associated with it)

2022-10-31 09:20 UTC, danwalmsley commented on src/Avalonia.Controls/TopLevel.cs
> +        public static readonly AttachedProperty<Color?> StatusBarColorProperty =
we can put this in its own file:

`<UserControl MobileStatusBar.Color="Red" />`

2022-10-31 21:52 UTC, danwalmsley requested changes
seems to be some leftover code.

2022-10-31 21:52 UTC, danwalmsley commented on src/Avalonia.Controls/TopLevel.cs
> +            var child = Content;
leftover?

2022-11-01 07:40 UTC, emmauss commented on src/Avalonia.Controls/TopLevel.cs
> +            var child = Content;
Yeah. Removed.

2022-11-01 08:10 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025556-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-01 11:26 UTC, emmauss commented
Replaced `StatusBarColor` with `StatusBarTheme`

2022-11-01 11:43 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025566-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-06 04:24 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025772-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-10 05:57 UTC, maxkatz6 commented on src/Avalonia.Controls/Platform/ITopLevelWithPlatformStatusBar.cs
> +    public interface ITopLevelWithPlatformStatusBar
```suggestion
    [Avalonia.Metadata.Unstable]
    public interface ITopLevelWithPlatformStatusBar
```

2022-11-10 06:44 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0025964-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-12-22 15:56 UTC, closed without merging