Resolve StyleInclude and ResourceInclude at compile time
AvaloniaUI/Avalonia pull request #9413
Opened 2022-11-11 06:46 UTC by maxkatz6

## What is the current behavior?

StyleInclude and ResourceInclude are resolved by URI and a if/else blocks. Because of that .NET linked can remove generated types, as nothing is using them by strong reference.

## What is the updated/expected behavior with this PR?

StyleInclude and ResourceInclude are replaced with direct factory/ctor method calls.

## Checklist

- [x] Replace StyleInclude and ResourceInclude with marker the on transform/emit stage
- [x] Replace marker methods with direct factory/ctor method calls
- [ ] Support ref dependency assemblies
- [ ] Update Fluent and Default theme to not use StyleInclude/ResourceInclude from the code behind

## Fixed issues

Fixes #2893
Fixes #9127

CC @kekekeks @kant2002

2022-11-12 08:23 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026098-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-13 19:29 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026128-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-13 20:51 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026132-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-14 14:38 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026171-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-17 02:34 UTC, maxkatz6 commented on src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StyleIncludeExtension.cs
> -    public class StyleIncludeExtension
I believe this class was needed in pre-XamlX era. Now compiled can resolve normal StyleInclude just fine.

2022-11-17 06:00 UTC, kekekeks requested changes

2022-11-18 05:24 UTC, maxkatz6 commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlAssetIncludeTransformer.cs
> +    private class AssetIncludeMethodNode : XamlAstNode, IXamlAstValueNode, IXamlAstILEmitableNode
Well, I need a RuntimeContext to transform relative paths. So, I would end up making on the of parameter nodes as emittable, which won't reduce any code or complexity in the end.

2022-11-18 05:48 UTC, maxkatz6 commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlAssetIncludeTransformer.cs
> +            // Source value can be set with markup extension instead of a text node, we don't support it here yet.
Done

2022-11-18 05:48 UTC, maxkatz6 commented on src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
> +                foreach (var (populateMethod, resourceFilePath) in populateMethodsToTransform)
Done

2022-11-18 06:33 UTC, maxkatz6 commented on src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlAssetIncludeTransformer.cs
> +            // Only "avares" protocol supported or relative paths.
Yeah, but we still use "test:" in the unit tests. So I can't just throw an error here without replacing 20 tests.

2022-11-18 07:02 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026320-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-18 07:23 UTC, kekekeks approved these changes

2022-11-18 15:48 UTC, merged

2022-11-18 15:52 UTC, avaloniaui-team commented
You can test this PR using the following package version. `11.0.999-cibuild0026354-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

2022-11-23 16:06 UTC, KieranDevvs commented
Im getting an IL linker error when publishing trimmed in .NET 7 & version `11.0.999-cibuild0026354-beta`:
![image](https://user-images.githubusercontent.com/21192520/203593539-31f1826d-6995-4333-b11b-d21e543d2616.png)

```
>------ Publish started: Project: AvaloniaTrimmingTest, Configuration: Release Any CPU ------
2>Determining projects to restore...
2>All projects are up-to-date for restore.
2>Could not extract the MVID from "obj\Release\net7.0\win-x64\refint\AvaloniaTrimmingTest.dll". Are you sure it is a reference assembly?
2>AvaloniaTrimmingTest -> C:\Users\kieran.devlin\Documents\git\sources\AvaloniaTrimmingTest\AvaloniaTrimmingTest\bin\Release\net7.0\win-x64\AvaloniaTrimmingTest.dll
2>Optimizing assemblies for size. This process might take a while.
2>C:\Program Files\dotnet\dotnet.exe "C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\tools\net7.0\illink.dll" -a "obj\Release\net7.0\win-x64\AvaloniaTrimmingTest.dll"
2>--singlewarn
2>--trim-mode Link
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Base.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Controls.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.DesignerSupport.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Dialogs.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Markup.Xaml.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Markup.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.MicroCom.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.OpenGL.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.desktop\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Desktop.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.freedesktop\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.FreeDesktop.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.native\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Native.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.reactiveui\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.ReactiveUI.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.remote.protocol\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Remote.Protocol.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.skia\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Skia.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.win32\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.Win32.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\avalonia.x11\11.0.999-cibuild0026507-beta\lib\net6.0\Avalonia.X11.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\dynamicdata\7.9.5\lib\net6.0\DynamicData.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\harfbuzzsharp\2.8.2.1-preview.108\lib\net6.0\HarfBuzzSharp.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\jetbrains.annotations\10.3.0\lib\netstandard1.0\JetBrains.Annotations.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microcom.runtime\0.11.0\lib\net5.0\MicroCom.Runtime.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.win32.systemevents\6.0.0\runtimes\win\lib\net6.0\Microsoft.Win32.SystemEvents.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\reactiveui\18.3.1\lib\net6.0\ReactiveUI.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\skiasharp\2.88.1\lib\net6.0\SkiaSharp.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\splat\14.4.1\lib\net6.0\Splat.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\system.drawing.common\6.0.0\runtimes\win\lib\net6.0\System.Drawing.Common.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\system.reactive\5.0.0\lib\net5.0\System.Reactive.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\tmds.dbus\0.9.0\lib\netstandard2.0\Tmds.DBus.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\Microsoft.CSharp.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\Microsoft.VisualBasic.Core.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\Microsoft.VisualBasic.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\Microsoft.Win32.Primitives.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\Microsoft.Win32.Registry.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.AppContext.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Buffers.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Collections.Concurrent.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Collections.Immutable.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Collections.NonGeneric.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Collections.Specialized.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Collections.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.Annotations.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.DataAnnotations.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.EventBasedAsync.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.Primitives.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.TypeConverter.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.ComponentModel.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Configuration.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Console.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Core.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Data.Common.dll"
2>-reference "C:\Users\kieran.devlin\.nuget\packages\microsoft.netcore.app.runtime.win-x64\7.0.0\runtimes\win-x64\lib\net7.0\System.Data.DataSetExtensions.dll"
2>-reference "C:\Users\kier [...]