fix: Update SharpDX Package
AvaloniaUI/Avalonia pull request #9606
Opened 2022-12-03 11:38 UTC by workgroupengineering

## What does the pull request do?

## What is the current behavior?

## What is the updated/expected behavior with this PR?

## How was the solution implemented (if it's not obvious)?

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

## Obsoletions / Deprecations

## Fixed issues

Fixes #9603

2022-12-03 12:12 UTC, maxkatz6 approved these changes

2022-12-04 16:20 UTC, maxkatz6 approved these changes

2022-12-06 04:47 UTC, maxkatz6 requested changes
Seems like tests are still failing

2022-12-14 22:16 UTC, grokys commented
Closing this then as it sounds like it's not a good idea.

2022-12-14 22:16 UTC, closed without merging